# -*- coding: utf-8 -*-
"""PCP A dias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqgRDwtQ5y_AhGMFYNWKNCfGz1u14wVa
"""

import pandas as pd

# 1. Cargar datos
df = pd.read_excel('datos entrada A dias.xlsx')
df.columns = [c.strip() for c in df.columns]
df['FECHA'] = pd.to_datetime(df['FECHA'])

# --- REGLA: PROMESA (3er día a las 15:00, saltando domingos) ---
def calcular_promesa(fecha_llegada):
    promesa = fecha_llegada + pd.Timedelta(days=2)
    if promesa.weekday() == 6: # Si es domingo, pasar al lunes
        promesa += pd.Timedelta(days=1)
    return promesa.replace(hour=15, minute=0, second=0)

df['FECHA_PROMESA'] = df['FECHA'].apply(calcular_promesa)

# --- SIMULACIÓN ---
df = df.sort_values(by='FECHA')
resumen_diario = []
todas_las_remisiones_procesadas = []
lista_pendientes = pd.DataFrame()

# Reloj global inicia el primer día a las 00:00
reloj_global = df['FECHA'].min().replace(hour=0, minute=0)
dias_unicos = sorted(df['FECHA'].unique())

for dia in dias_unicos:
    dia_actual = pd.to_datetime(dia)

    # Si es domingo, el taller no abre.
    if dia_actual.weekday() == 6:
        continue

    # Cargar pedidos del día y unir con pendientes de ayer
    nuevos = df[df['FECHA'] == dia_actual].copy()
    pool = pd.concat([lista_pendientes, nuevos])

    # REGLA SPT: Ordenar por p_j de menor a mayor
    secuencia = pool.sort_values(by='p_j').reset_index(drop=True)

    terminados_hoy = []
    indices_procesados = []
    limite_dia = dia_actual + pd.Timedelta(hours=24)

    # Sincronizar reloj al inicio del día si estaba atrasado
    if reloj_global < dia_actual:
        reloj_global = dia_actual

    for i, fila in secuencia.iterrows():
        # ¿El trabajo cabe en las 24h de hoy?
        if reloj_global + pd.Timedelta(hours=fila['p_j']) > limite_dia:
            break

        reloj_global += pd.Timedelta(hours=fila['p_j'])

        # Saltar domingo en producción si el reloj cae ahí
        if reloj_global.weekday() == 6:
            reloj_global += pd.Timedelta(days=1)

        # TIEMPO DE FLUJO: Desde que llegó la remisión hasta que terminó realmente
        tiempo_flujo = (reloj_global - fila['FECHA']).total_seconds() / 3600
        retrasado = reloj_global > fila['FECHA_PROMESA']

        info = fila.copy()
        info['FECHA_FIN_REAL'] = reloj_global
        info['TIEMPO_FLUJO'] = tiempo_flujo
        info['RETRASADO'] = retrasado

        terminados_hoy.append(info)
        todas_las_remisiones_procesadas.append(info)
        indices_procesados.append(i)

    # CORRECCIÓN DEL ERROR: Actualizar pendientes eliminando los procesados por posición
    lista_pendientes = secuencia.drop(indices_procesados)

    if terminados_hoy:
        df_hoy = pd.DataFrame(terminados_hoy)
        resumen_diario.append({
            'Día': dia_actual.strftime('%Y-%m-%d'),
            'Procesados': len(df_hoy),
            'Flujo_Prom_Día': round(df_hoy['TIEMPO_FLUJO'].mean(), 2),
            'A_Tiempo': (df_hoy['RETRASADO'] == False).sum(),
            'Retrasados': (df_hoy['RETRASADO'] == True).sum(),
            'Pendientes_Cierre': len(lista_pendientes)
        })

# --- RESULTADOS FINALES ---
df_resumen = pd.DataFrame(resumen_diario)
df_maestro = pd.DataFrame(todas_las_remisiones_procesadas)

print("--- RESULTADOS DE LA PROGRAMACIÓN SPT ---")
print(df_resumen)
print(f"\nOBJETIVO GLOBAL - TIEMPO DE FLUJO PROMEDIO: {df_maestro['TIEMPO_FLUJO'].mean():.2f} horas")

# --- FUNCIONES DE CONSULTA ---

def consultar_remision(n_remision):
    """Busca una remisión por número"""
    res = df_maestro[df_maestro['Nº REMISION'] == n_remision]
    if not res.empty:
        return res[['Nº REMISION', 'FECHA', 'FECHA_PROMESA', 'FECHA_FIN_REAL', 'TIEMPO_FLUJO', 'RETRASADO']]
    return f"Remisión {n_remision} no encontrada."

def consultar_dia(fecha_str):
    """Ver entregas de un día ('YYYY-MM-DD')"""
    res = df_maestro[df_maestro['FECHA_FIN_REAL'].dt.strftime('%Y-%m-%d') == fecha_str]
    return res[['Nº REMISION', 'p_j', 'FECHA_FIN_REAL', 'RETRASADO']] if not res.empty else "Sin entregas."

import pandas as pd

# 1. Cargar datos desde el archivo subido a Colab
df = pd.read_excel('datos entrada A dias.xlsx')
df.columns = [c.strip() for c in df.columns]
df['FECHA'] = pd.to_datetime(df['FECHA'])

# --- REGLA: PROMESA (2 días hábiles después, entrega al 3ro a las 15:00) ---
def calcular_promesa(fecha_llegada):
    promesa = fecha_llegada + pd.Timedelta(days=2)
    if promesa.weekday() == 6: # Si cae domingo, se entrega el lunes
        promesa += pd.Timedelta(days=1)
    return promesa.replace(hour=15, minute=0, second=0)

df['FECHA_PROMESA'] = df['FECHA'].apply(calcular_promesa)

# --- SIMULACIÓN DE PROGRAMACIÓN SPT ---
df = df.sort_values(by='FECHA')
resumen_diario = []
todas_las_remisiones_procesadas = []
lista_pendientes = pd.DataFrame()

# Reloj del taller (inicia a las 00:00 del primer día de datos)
reloj_global = df['FECHA'].min().replace(hour=0, minute=0)
dias_unicos = sorted(df['FECHA'].unique())

for dia in dias_unicos:
    dia_actual = pd.to_datetime(dia)

    # El domingo no hay producción (se salta el día en el calendario)
    if dia_actual.weekday() == 6:
        continue

    # 1. Recoger pedidos nuevos y unir con los pendientes de ayer
    nuevos = df[df['FECHA'] == dia_actual].copy()
    pool = pd.concat([lista_pendientes, nuevos])

    # 2. Aplicar Regla SPT (Shortest Processing Time)
    secuencia = pool.sort_values(by='p_j').reset_index(drop=True)

    terminados_hoy = []
    indices_procesados = []
    limite_dia = dia_actual + pd.Timedelta(hours=24)

    # Sincronizar reloj si el taller terminó temprano el día anterior
    if reloj_global < dia_actual:
        reloj_global = dia_actual

    for i, fila in secuencia.iterrows():
        # ¿El trabajo cabe en el turno de 24h de hoy?
        if reloj_global + pd.Timedelta(hours=fila['p_j']) > limite_dia:
            break

        reloj_global += pd.Timedelta(hours=fila['p_j'])

        # Saltar domingo en la línea de producción
        if reloj_global.weekday() == 6:
            reloj_global += pd.Timedelta(days=1)

        # TIEMPO DE FLUJO (Fj): Tiempo total desde que llegó hasta que se terminó
        tiempo_flujo = (reloj_global - fila['FECHA']).total_seconds() / 3600
        retrasado = reloj_global > fila['FECHA_PROMESA']

        info = fila.copy()
        info['FECHA_FIN_REAL'] = reloj_global
        info['TIEMPO_FLUJO'] = tiempo_flujo
        info['RETRASADO'] = retrasado

        terminados_hoy.append(info)
        todas_las_remisiones_procesadas.append(info)
        indices_procesados.append(i)

    # 3. Los que no se alcanzaron a hacer quedan como pendientes para mañana
    lista_pendientes = secuencia.drop(indices_procesados)

    # 4. Cálculo de Indicadores Diarios
    if terminados_hoy:
        df_hoy = pd.DataFrame(terminados_hoy)
        resumen_diario.append({
            'Día': dia_actual.strftime('%Y-%m-%d'),
            'Total_Remisiones': len(df_hoy),
            'Prom_Flujo_Horas': round(df_hoy['TIEMPO_FLUJO'].mean(), 2), # Literal A
            'A_Tiempo': (df_hoy['RETRASADO'] == False).sum(),
            'Con_Retraso': (df_hoy['RETRASADO'] == True).sum(),
            'Backlog_Pendiente': len(lista_pendientes)
        })

# --- TABLAS DE RESULTADOS ---
df_resumen = pd.DataFrame(resumen_diario)
df_maestro = pd.DataFrame(todas_las_remisiones_procesadas)

# Mostrar la tabla principal de indicadores
print("### RESUMEN DE DESEMPEÑO DIARIO ###")
print(df_resumen.to_string(index=False))

# --- MÓDULO DE CONSULTA POR REMISIÓN ---
def consultar_remision(n_remision):
    """
    Busca una remisión y explica claramente el cumplimiento.
    """
    # Buscamos en el histórico total
    res = df_maestro[df_maestro['Nº REMISION'] == n_remision].copy()

    if not res.empty:
        fila = res.iloc[0]
        promesa = fila['FECHA_PROMESA']
        finalizacion = fila['FECHA_FIN_REAL']

        # Calcular la diferencia de tiempo
        diferencia = promesa - finalizacion
        horas_diff = abs(diferencia.total_seconds()) / 3600
        h = int(horas_diff)
        m = int((horas_diff - h) * 60)

        estado = "✅ A TIEMPO" if finalizacion <= promesa else "❌ RETRASADO"
        margen = "antes de lo previsto" if finalizacion <= promesa else "después de la promesa"

        print(f"\n{'='*50}")
        print(f"DETALLE DE REMISIÓN: {n_remision}")
        print(f"{'='*50}")
        print(f"Llegada del pedido:  {fila['FECHA'].strftime('%Y-%m-%d %H:%M')}")
        print(f"Promesa de entrega:  {promesa.strftime('%Y-%m-%d %H:%M')}")
        print(f"Finalización real:   {finalizacion.strftime('%Y-%m-%d %H:%M')}")
        print(f"Tiempo de Flujo:     {round(fila['TIEMPO_FLUJO'], 2)} horas")
        print(f"{'-'*50}")
        print(f"ESTADO: {estado}")
        print(f"DIFERENCIA: El pedido se terminó {h}h {m}m {margen}.")
        print(f"{'='*50}")
    else:
        print(f"\nLa remisión {n_remision} no se encuentra en el registro o sigue en producción.")

# Ejemplo de uso:
# consultar_remision(1000017081)
consultar_remision (1000016976)

import pandas as pd

# 1. Cargar datos
df = pd.read_excel('datos entrada A dias.xlsx')
df.columns = [c.strip() for c in df.columns]
df['FECHA'] = pd.to_datetime(df['FECHA'])

# --- REGLA: PROMESA (3er día a las 15:00, saltando domingos) ---
def calcular_promesa(fecha_llegada):
    promesa = fecha_llegada + pd.Timedelta(days=2)
    if promesa.weekday() == 6:
        promesa += pd.Timedelta(days=1)
    return promesa.replace(hour=15, minute=0, second=0)

df['FECHA_PROMESA'] = df['FECHA'].apply(calcular_promesa)

# --- CONFIGURACIÓN DE MÁQUINAS ---
def simular_taller(datos, col_pj):
    # Filtrar solo las remisiones que tienen carga para esta máquina
    datos_maq = datos[datos[col_pj] > 0].copy()
    datos_maq = datos_maq.sort_values(by='FECHA')

    # Calcular Índice WSPT (pj / Cant tipos)
    datos_maq['WSPT_INDEX'] = datos_maq[col_pj] / datos_maq['Cant tipos']

    reloj = datos_maq['FECHA'].min().replace(hour=0, minute=0, second=0)
    lista_pendientes = pd.DataFrame()
    procesados = []
    dias_unicos = sorted(datos['FECHA'].unique())

    reporte_diario = {}

    for dia in dias_unicos:
        dia_actual = pd.to_datetime(dia)
        if dia_actual.weekday() == 6: continue

        nuevos = datos_maq[datos_maq['FECHA'] == dia_actual].copy()
        pool = pd.concat([lista_pendientes, nuevos])

        # APLICACIÓN WSPT: Menor índice primero
        secuencia = pool.sort_values(by='WSPT_INDEX').reset_index(drop=True)

        terminados_hoy = []
        indices_ok = []
        limite_dia = dia_actual + pd.Timedelta(hours=24)

        if reloj < dia_actual: reloj = dia_actual

        for i, fila in secuencia.iterrows():
            if reloj + pd.Timedelta(hours=fila[col_pj]) > limite_dia: break

            reloj += pd.Timedelta(hours=fila[col_pj])
            if reloj.weekday() == 6: reloj += pd.Timedelta(days=1)

            info = fila.copy()
            info['FIN_REAL'] = reloj
            info['FLUJO'] = (reloj - fila['FECHA']).total_seconds() / 3600
            info['RETRASADO'] = reloj > fila['FECHA_PROMESA']
            procesados.append(info)
            terminados_hoy.append(info)
            indices_ok.append(i)

        lista_pendientes = secuencia.drop(indices_ok)
        reporte_diario[dia_actual.strftime('%Y-%m-%d')] = {
            'completados': len(terminados_hoy),
            'pendientes': len(lista_pendientes),
            'flujo_prom': pd.DataFrame(terminados_hoy)['FLUJO'].mean() if terminados_hoy else 0
        }

    return pd.DataFrame(procesados), reporte_diario

# --- EJECUCIÓN ---
df_fig, reporte_fig = simular_taller(df, 'pj fig')
df_mall, reporte_mall = simular_taller(df, 'pj mall')

# Consolidado de todas las remisiones para consultas
df_maestro = pd.concat([df_fig, df_mall]).drop_duplicates(subset=['Nº REMISION'], keep='last')

# --- REPORTE CONSOLIDADO DIARIO ---
dias_reporte = sorted(list(set(reporte_fig.keys()) | set(reporte_mall.keys())))
resumen_final = []

for d in dias_reporte:
    fig = reporte_fig.get(d, {'completados': 0, 'pendientes': 0, 'flujo_prom': 0})
    mall = reporte_mall.get(d, {'completados': 0, 'pendientes': 0, 'flujo_prom': 0})

    resumen_final.append({
        'Fecha': d,
        'Fig_Hechos': fig['completados'],
        'Fig_Pend': fig['pendientes'],
        'Mall_Hechos': mall['completados'],
        'Mall_Pend': mall['pendientes'],
        'Flujo_Prom_Dia': round((fig['flujo_prom'] + mall['flujo_prom']) / 2, 2)
    })

print("### CONSOLIDADO DIARIO DE OPERACIONES (WSPT) ###")
print(pd.DataFrame(resumen_final).to_string(index=False))

# --- MÓDULO DE CONSULTA ---
def consultar_remision(n_remision):
    """
    Busca la remisión en ambas máquinas y determina el cumplimiento final.
    """
    # Buscar en los resultados de ambas máquinas
    res_fig = df_fig[df_fig['Nº REMISION'] == n_remision]
    res_mall = df_mall[df_mall['Nº REMISION'] == n_remision]

    if res_fig.empty and res_mall.empty:
        print(f"⚠️ La remisión {n_remision} no se encuentra procesada aún (está en Backlog o no existe).")
        return

    # Obtener los datos (si existen en la máquina)
    fin_fig = res_fig.iloc[0]['FIN_REAL'] if not res_fig.empty else None
    fin_mall = res_mall.iloc[0]['FIN_REAL'] if not res_mall.empty else None
    promesa = (res_fig.iloc[0] if not res_fig.empty else res_mall.iloc[0])['FECHA_PROMESA']

    # La fecha de entrega real es la mayor de las dos (cuando se completa todo)
    fechas_fin = [f for f in [fin_fig, fin_mall] if f is not None]
    entrega_final = max(fechas_fin)

    # Cálculo de diferencia
    diff = promesa - entrega_final
    horas = abs(diff.total_seconds()) / 3600
    estado = "✅ A TIEMPO" if entrega_final <= promesa else "❌ RETRASADO"

    print(f"\n{'='*60}")
    print(f"CONSULTA DE CLIENTE - REMISIÓN: {n_remision}")
    print(f"{'='*60}")
    if fin_fig: print(f"Finalizado en Figurado: {fin_fig.strftime('%Y-%m-%d %H:%M')}")
    if fin_mall: print(f"Finalizado en Mallas:   {fin_mall.strftime('%Y-%m-%d %H:%M')}")
    print(f"{'-'*60}")
    print(f"PROMESA DE ENTREGA:    {promesa.strftime('%Y-%m-%d %H:%M')}")
    print(f"ENTREGA TOTAL REAL:    {entrega_final.strftime('%Y-%m-%d %H:%M')}")
    print(f"ESTADO FINAL:          {estado}")
    print(f"DIFERENCIA:            {int(horas)}h {int((horas%1)*60)}m ({'antes' if entrega_final <= promesa else 'después'})")
    print(f"{'='*60}")

# Prueba ahora con:
# consultar_remision(1000017081)
consultar_remision(1000018090)





import pandas as pd

# 1. CARGA DE DATOS
archivo = 'datos entrada A dias.xlsx'
df = pd.read_excel(archivo)
df.columns = [c.strip() for c in df.columns]
df['FECHA'] = pd.to_datetime(df['FECHA'])

# 2. CONFIGURACIÓN DE PROMESA
def calcular_promesa(rj):
    p = rj + pd.Timedelta(days=2)
    if p.weekday() == 6: p += pd.Timedelta(days=1)
    return p.replace(hour=15, minute=0, second=0)

df['FECHA_PROMESA'] = df['FECHA'].apply(calcular_promesa)

# 3. MOTOR DE CÁLCULO
def procesar_maquina(datos, col_pj):
    df_m = datos[datos[col_pj] > 0].copy()
    df_m['WSPT'] = df_m[col_pj] / df_m['Cant tipos']
    reloj = df_m['FECHA'].min().replace(hour=0, minute=0)
    backlog, finalizados, resumen_diario = pd.DataFrame(), [], []
    hoy = df_m['FECHA'].min()
    ultima_fecha_datos = df_m['FECHA'].max()

    while hoy <= ultima_fecha_datos or not backlog.empty:
        if hoy.weekday() == 6:
            hoy += pd.Timedelta(days=1)
            continue

        pool = pd.concat([backlog, df_m[df_m['FECHA'] == hoy]])
        if not pool.empty:
            pool = pool.sort_values(by=['WSPT'], kind='stable')
            horas_hoy, hechos_hoy, ids_terminados = 0, 0, []
            if reloj < hoy: reloj = hoy

            for idx, row in pool.iterrows():
                tiempo_tarea = row[col_pj]
                if horas_hoy > 0 and (horas_hoy + tiempo_tarea > 24): break

                reloj += pd.Timedelta(hours=tiempo_tarea)
                horas_hoy += tiempo_tarea
                if reloj.weekday() == 6: reloj += pd.Timedelta(days=1)

                row_copy = row.copy()
                row_copy['FIN_REAL'] = reloj
                finalizados.append(row_copy)
                ids_terminados.append(idx)
                hechos_hoy += 1
                if horas_hoy >= 24: break

            backlog = pool.drop(ids_terminados)
            resumen_diario.append({'Fecha': hoy.date(), 'Hechos': hechos_hoy, 'Pendientes': len(backlog)})
        hoy += pd.Timedelta(days=1)
        if hoy > ultima_fecha_datos + pd.Timedelta(days=100): break

    return pd.DataFrame(finalizados), pd.DataFrame(resumen_diario)

# 4. EJECUCIÓN INICIAL
print("⚙️ Procesando modelos de Figurado y Mallas...")
res_fig, stat_fig = procesar_maquina(df, 'pj fig')
res_mall, stat_mall = procesar_maquina(df, 'pj mall')

consolidado = stat_fig.merge(stat_mall, on='Fecha', how='outer', suffixes=('_Fig', '_Mall')).fillna(0)
consolidado['Flujo_Prom_Dia'] = ((consolidado['Hechos_Fig'] + consolidado['Hechos_Mall']) / 2).round(2)

# --- NUEVA FUNCIÓN: CÁLCULO DE TIEMPO DE FLUJO PROMEDIO ---
def calcular_tiempo_flujo_global():
    # Consolidamos el fin de cada remisión (máximo entre figurado y mallas)
    f_res = res_fig[['Nº REMISION', 'FECHA', 'FIN_REAL']]
    m_res = res_mall[['Nº REMISION', 'FECHA', 'FIN_REAL']]

    total = pd.merge(f_res, m_res, on=['Nº REMISION', 'FECHA'], how='outer', suffixes=('_f', '_m'))

    # El tiempo de salida real es el último proceso terminado
    total['SALIDA_FINAL'] = total[['FIN_REAL_f', 'FIN_REAL_m']].max(axis=1)

    # Tiempo de Flujo = Salida - Llegada (convertido a días)
    total['TIEMPO_FLUJO'] = (total['SALIDA_FINAL'] - total['FECHA']).dt.total_seconds() / (24 * 3600)

    return round(total['TIEMPO_FLUJO'].mean(), 2)

# 5. MENÚ INTERACTIVO POR CONSOLA
def menu():
    while True:
        print("\n" + "=".center(50, "="))
        print(" SISTEMA DE GESTIÓN DE TALLER (WSPT) ".center(50))
        print("=".center(50, "="))
        print("1. Consultar estado de una Remisión")
        print("2. Ver secuencia de remisiones por día")
        print("3. Ver consolidado general (Hechos/Pendientes)")
        print("4. Ver Tiempo de Flujo Promedio (Horizonte Total)")
        print("5. Salir")

        opcion = input("\nSeleccione una opción: ")

        if opcion == "1":
            n = input("Ingrese el Nº de Remisión: ").strip()
            f = res_fig[res_fig['Nº REMISION'].astype(str) == n]
            m = res_mall[res_mall['Nº REMISION'].astype(str) == n]

            if f.empty and m.empty:
                print(f"⚠️ Remisión {n} no encontrada.")
            else:
                f_fin = f['FIN_REAL'].max() if not f.empty else pd.Timestamp.min
                m_fin = m['FIN_REAL'].max() if not m.empty else pd.Timestamp.min
                final = max(f_fin, m_fin)
                promesa = (f.iloc[0] if not f.empty else m.iloc[0])['FECHA_PROMESA']
                print(f"\n--- REPORTE DE REMISIÓN {n} ---")
                print(f"Estado: {'✅ A TIEMPO' if final <= promesa else '❌ RETRASADO'}")
                print(f"Promesa: {promesa.strftime('%Y-%m-%d %H:%M')}")
                print(f"Entrega: {final.strftime('%Y-%m-%d %H:%M')}")

        elif opcion == "2":
            fecha_buscada = input("Ingrese la fecha (AAAA-MM-DD): ").strip()
            try:
                dia_f = res_fig[res_fig['FIN_REAL'].dt.strftime('%Y-%m-%d') == fecha_buscada]
                dia_m = res_mall[res_mall['FIN_REAL'].dt.strftime('%Y-%m-%d') == fecha_buscada]
                print(f"\n--- SECUENCIA DEL DÍA {fecha_buscada} ---")
                print(f"Figurado: {dia_f['Nº REMISION'].tolist() if not dia_f.empty else 'Sin actividad'}")
                print(f"Mallas:   {dia_m['Nº REMISION'].tolist() if not dia_m.empty else 'Sin actividad'}")
            except:
                print("⚠️ Formato de fecha incorrecto.")

        elif opcion == "3":
            print("\n--- CONSOLIDADO DE OPERACIONES ---")
            cols = ['Fecha', 'Hechos_Fig', 'Pendientes_Fig', 'Hechos_Mall', 'Pendientes_Mall', 'Flujo_Prom_Dia']
            print(consolidado[cols].to_string(index=False))

        elif opcion == "4":
            promedio_dias = calcular_tiempo_flujo_global()
            print("\n" + "-"*50)
            print(f"📊 TIEMPO DE FLUJO PROMEDIO GLOBAL: {promedio_dias} días")
            print(" (Promedio de permanencia desde rj hasta despacho)")
            print("-"*50)

        elif opcion == "5":
            print("Saliendo del sistema...")
            break
        else:
            print("⚠️ Opción no válida.")

# Iniciar el menú
menu()

import pandas as pd
import numpy as np

# 1. CARGA DE DATOS
archivo = 'datos entrada A dias.xlsx'
df = pd.read_excel(archivo)
df.columns = [c.strip() for c in df.columns]
df['FECHA'] = pd.to_datetime(df['FECHA'])

# 2. CONFIGURACIÓN DE PROMESA
def calcular_promesa(rj):
    p = rj + pd.Timedelta(days=2)
    if p.weekday() == 6: p += pd.Timedelta(days=1)
    return p.replace(hour=15, minute=0, second=0)

df['FECHA_PROMESA'] = df['FECHA'].apply(calcular_promesa)

# 3. MOTOR DE CÁLCULO
def procesar_maquina(datos, col_pj):
    df_m = datos[datos[col_pj] > 0].copy()
    df_m['WSPT'] = df_m[col_pj] / df_m['Cant tipos']
    reloj = df_m['FECHA'].min().replace(hour=0, minute=0)
    backlog, finalizados, resumen_diario = pd.DataFrame(), [], []
    hoy = df_m['FECHA'].min()
    ultima_fecha_datos = df_m['FECHA'].max()

    while hoy <= ultima_fecha_datos or not backlog.empty:
        if hoy.weekday() == 6:
            hoy += pd.Timedelta(days=1)
            continue

        pool = pd.concat([backlog, df_m[df_m['FECHA'] == hoy]])
        if not pool.empty:
            pool = pool.sort_values(by=['WSPT'], kind='stable')
            horas_hoy, hechos_hoy, ids_terminados = 0, 0, []
            if reloj < hoy: reloj = hoy

            for idx, row in pool.iterrows():
                tiempo_tarea = row[col_pj]
                if horas_hoy > 0 and (horas_hoy + tiempo_tarea > 24): break

                reloj += pd.Timedelta(hours=tiempo_tarea)
                horas_hoy += tiempo_tarea
                if reloj.weekday() == 6: reloj += pd.Timedelta(days=1)

                row_copy = row.copy()
                row_copy['FIN_REAL'] = reloj
                row_copy['SEMANA'] = reloj.isocalendar()[1]
                finalizados.append(row_copy)
                ids_terminados.append(idx)
                hechos_hoy += 1
                if horas_hoy >= 24: break

            backlog = pool.drop(ids_terminados)
            resumen_diario.append({
                'Fecha': hoy.date(),
                'Semana': hoy.isocalendar()[1],
                'Hechos': hechos_hoy,
                'Pendientes': len(backlog)
            })
        hoy += pd.Timedelta(days=1)
        if hoy > ultima_fecha_datos + pd.Timedelta(days=100): break

    return pd.DataFrame(finalizados), pd.DataFrame(resumen_diario)

# 4. EJECUCIÓN
res_fig, stat_fig = procesar_maquina(df, 'pj fig')
res_mall, stat_mall = procesar_maquina(df, 'pj mall')

# 5. CÁLCULO DE TIEMPO DE FLUJO (EN HORAS)
def calcular_tiempo_flujo_horas():
    f_res = res_fig[['Nº REMISION', 'FECHA', 'FIN_REAL']]
    m_res = res_mall[['Nº REMISION', 'FECHA', 'FIN_REAL']]
    total = pd.merge(f_res, m_res, on=['Nº REMISION', 'FECHA'], how='outer', suffixes=('_f', '_m'))
    total['SALIDA_FINAL'] = total[['FIN_REAL_f', 'FIN_REAL_m']].max(axis=1)

    # Diferencia en horas totales
    total['TIEMPO_FLUJO_HORAS'] = (total['SALIDA_FINAL'] - total['FECHA']).dt.total_seconds() / 3600
    return round(total['TIEMPO_FLUJO_HORAS'].mean(), 2)

# 6. CONSOLIDADO SEMANAL
def obtener_semanal():
    sem_f = stat_fig.groupby('Semana').agg({'Hechos': 'sum', 'Pendientes': 'last'}).reset_index()
    sem_m = stat_mall.groupby('Semana').agg({'Hechos': 'sum', 'Pendientes': 'last'}).reset_index()
    return sem_f.merge(sem_m, on='Semana', suffixes=('_Fig', '_Mall'))

# 7. MENÚ
def menu():
    while True:
        print("\n" + "=".center(50, "="))
        print(" CONTROL DE PRODUCCIÓN SEMANAL ".center(50))
        print("=".center(50, "="))
        print("1. Consultar Remisión")
        print("2. Consolidado DIARIO")
        print("3. Consolidado SEMANAL")
        print("4. Promedio de Flujo Total (HORAS)")
        print("5. Salir")

        op = input("\nSeleccione: ")
        if op == "1":
            n = input("Nº Remisión: ").strip()
            # ... (lógica de búsqueda igual a la anterior)
        elif op == "2":
            print(stat_fig.merge(stat_mall, on='Fecha', suffixes=('_Fig', '_Mall')).to_string(index=False))
        elif op == "3":
            print(obtener_semanal().to_string(index=False))
        elif op == "4":
            print(f"\n>>> TIEMPO DE FLUJO PROMEDIO: {calcular_tiempo_flujo_horas()} HORAS")
        elif op == "5": break

menu()

import pandas as pd

# 1. CARGA DE DATOS
archivo = 'datos entrada A dias.xlsx'
df = pd.read_excel(archivo)
df.columns = [c.strip() for c in df.columns]
df['FECHA'] = pd.to_datetime(df['FECHA'])

# 2. CONFIGURACIÓN DE PROMESA (2 días hábiles)
def calcular_promesa(rj):
    p = rj + pd.Timedelta(days=2)
    if p.weekday() == 6: p += pd.Timedelta(days=1)
    return p.replace(hour=15, minute=0, second=0)

df['FECHA_PROMESA'] = df['FECHA'].apply(calcular_promesa)

# 3. MOTOR DE CÁLCULO MEJORADO
def procesar_maquina(datos, col_pj):
    df_m = datos[datos[col_pj] > 0].copy()
    # WSPT con desempate: Prioriza pedidos con más tipos de producto si el WSPT es igual
    df_m['WSPT'] = df_m[col_pj] / df_m['Cant tipos']

    reloj = df_m['FECHA'].min().replace(hour=0, minute=0)
    backlog, finalizados, resumen_diario = pd.DataFrame(), [], []
    hoy = df_m['FECHA'].min()
    ultima_fecha_datos = df_m['FECHA'].max()

    while hoy <= ultima_fecha_datos or not backlog.empty:
        if hoy.weekday() == 6:
            hoy += pd.Timedelta(days=1)
            continue

        nuevos = df_m[df_m['FECHA'] == hoy]
        pool = pd.concat([backlog, nuevos])

        if not pool.empty:
            # Ordenamos por WSPT y desempate por 'Cant tipos' de forma descendente para sacar lo complejo rápido
            pool = pool.sort_values(by=['WSPT', 'Cant tipos'], ascending=[True, False], kind='stable')

            horas_hoy, hechos_hoy, ids_terminados = 0, 0, []
            if reloj < hoy: reloj = hoy

            for idx, row in pool.iterrows():
                tiempo_tarea = row[col_pj]
                if horas_hoy > 0 and (horas_hoy + tiempo_tarea > 24): break

                reloj += pd.Timedelta(hours=tiempo_tarea)
                horas_hoy += tiempo_tarea
                if reloj.weekday() == 6: reloj += pd.Timedelta(days=1)

                row_copy = row.copy()
                row_copy['FIN_REAL'] = reloj
                row_copy['SEMANA'] = reloj.isocalendar()[1]
                finalizados.append(row_copy)
                ids_terminados.append(idx)
                hechos_hoy += 1
                if horas_hoy >= 24: break

            backlog = pool.drop(ids_terminados)
            resumen_diario.append({'Fecha': hoy.date(), 'Semana': hoy.isocalendar()[1], 'Hechos': hechos_hoy, 'Pendientes': len(backlog)})

        hoy += pd.Timedelta(days=1)
        if hoy > ultima_fecha_datos + pd.Timedelta(days=100): break

    return pd.DataFrame(finalizados), pd.DataFrame(resumen_diario)

# 4. EJECUCIÓN
res_fig, stat_fig = procesar_maquina(df, 'pj fig')
res_mall, stat_mall = procesar_maquina(df, 'pj mall')

# 5. CÁLCULO DE FLUJO DESCONTANDO DOMINGOS
def calcular_tiempo_flujo_horas_habiles():
    f_res = res_fig[['Nº REMISION', 'FECHA', 'FIN_REAL']]
    m_res = res_mall[['Nº REMISION', 'FECHA', 'FIN_REAL']]
    total = pd.merge(f_res, m_res, on=['Nº REMISION', 'FECHA'], how='outer', suffixes=('_f', '_m'))
    total['SALIDA_FINAL'] = total[['FIN_REAL_f', 'FIN_REAL_m']].max(axis=1)

    tiempos = []
    for _, row in total.iterrows():
        llegada = row['FECHA']
        salida = row['SALIDA_FINAL']
        # Calculamos días totales y restamos los domingos en ese rango
        dias_rango = pd.date_range(start=llegada.date(), end=salida.date(), freq='D')
        domingos = sum(1 for d in dias_rango if d.weekday() == 6)

        # Horas totales - (24 * número de domingos)
        horas_puras = (salida - llegada).total_seconds() / 3600
        horas_habiles = horas_puras - (domingos * 24)
        tiempos.append(max(0, horas_habiles))

    return round(sum(tiempos) / len(tiempos), 2)

# 6. CONSOLIDADO SEMANAL
def obtener_semanal():
    sem_f = stat_fig.groupby('Semana').agg({'Hechos': 'sum', 'Pendientes': 'last'}).reset_index()
    sem_m = stat_mall.groupby('Semana').agg({'Hechos': 'sum', 'Pendientes': 'last'}).reset_index()
    return sem_f.merge(sem_m, on='Semana', suffixes=('_Fig', '_Mall'))

# 7. MENÚ
def menu():
    while True:
        print("\n" + "=".center(50, "="))
        print(" GESTIÓN TALLER: FOCO EN TIEMPO DE FLUJO ".center(50))
        print("=".center(50, "="))
        print("1. Consolidado DIARIO")
        print("2. Consolidado SEMANAL")
        print("3. TIEMPO DE FLUJO PROMEDIO (HORAS HÁBILES)")
        print("4. Salir")

        op = input("\nSeleccione: ")
        if op == "1":
            print(stat_fig.merge(stat_mall, on='Fecha', suffixes=('_Fig', '_Mall')).to_string(index=False))
        elif op == "2":
            print(obtener_semanal().to_string(index=False))
        elif op == "3":
            print(f"\n>>> FLUJO PROMEDIO (Sin Domingos): {calcular_tiempo_flujo_horas_habiles()} HORAS")
        elif op == "4": break

menu()

import pandas as pd
import plotly.express as px
from datetime import datetime

# 1. CARGA DE DATOS
# Asegúrate de que el archivo 'datos entrada A dias.xlsx' esté en la misma carpeta
archivo = 'datos entrada A dias.xlsx'
df = pd.read_excel(archivo)
df.columns = [c.strip() for c in df.columns]
df['FECHA'] = pd.to_datetime(df['FECHA'])
df['Nº REMISION'] = df['Nº REMISION'].astype(str).str.strip()

# 2. CONFIGURACIÓN DE PROMESA (2 días hábiles)
def calcular_promesa(rj):
    p = rj + pd.Timedelta(days=2)
    if p.weekday() == 6: p += pd.Timedelta(days=1)
    return p.replace(hour=15, minute=0, second=0)

df['FECHA_PROMESA'] = df['FECHA'].apply(calcular_promesa)

# 3. MOTOR DE CÁLCULO WSPT (Prioridad y Secuencia)
def procesar_maquina(datos, col_pj):
    df_m = datos[datos[col_pj] > 0].copy()
    df_m['WSPT'] = df_m[col_pj] / df_m['Cant tipos']

    reloj = df_m['FECHA'].min().replace(hour=0, minute=0)
    backlog, finalizados, resumen_diario = pd.DataFrame(), [], []
    hoy = df_m['FECHA'].min()
    ultima_fecha_datos = df_m['FECHA'].max()

    while hoy <= ultima_fecha_datos or not backlog.empty:
        if hoy.weekday() == 6:
            hoy += pd.Timedelta(days=1)
            continue

        nuevos = df_m[df_m['FECHA'] == hoy]
        pool = pd.concat([backlog, nuevos])

        if not pool.empty:
            # Orden por WSPT y desempate por cantidad de tipos (complejidad)
            pool = pool.sort_values(by=['WSPT', 'Cant tipos'], ascending=[True, False], kind='stable')

            horas_hoy, hechos_hoy, ids_terminados = 0, 0, []
            if reloj < hoy: reloj = hoy

            for idx, row in pool.iterrows():
                tiempo_tarea = row[col_pj]
                if horas_hoy > 0 and (horas_hoy + tiempo_tarea > 24): break

                inicio_tarea = reloj
                reloj += pd.Timedelta(hours=tiempo_tarea)
                horas_hoy += tiempo_tarea
                if reloj.weekday() == 6: reloj += pd.Timedelta(days=1)

                row_copy = row.copy()
                row_copy['INICIO_REAL'] = inicio_tarea
                row_copy['FIN_REAL'] = reloj
                row_copy['SEMANA'] = inicio_tarea.isocalendar()[1]
                finalizados.append(row_copy)
                ids_terminados.append(idx)
                hechos_hoy += 1
                if horas_hoy >= 24: break

            backlog = pool.drop(ids_terminados)
            resumen_diario.append({'Fecha': hoy.date(), 'Semana': hoy.isocalendar()[1],
                                   'Hechos': hechos_hoy, 'Pendientes': len(backlog)})

        hoy += pd.Timedelta(days=1)
        if hoy > ultima_fecha_datos + pd.Timedelta(days=100): break

    return pd.DataFrame(finalizados), pd.DataFrame(resumen_diario)

# Ejecución de motores de Figurado y Mallas
res_fig, stat_fig = procesar_maquina(df, 'pj fig')
res_mall, stat_mall = procesar_maquina(df, 'pj mall')

# 4. CÁLCULO DE FLUJO PROMEDIO (Descontando Domingos)
def calcular_tiempo_flujo_horas_habiles():
    f_res = res_fig[['Nº REMISION', 'FECHA', 'FIN_REAL']]
    m_res = res_mall[['Nº REMISION', 'FECHA', 'FIN_REAL']]
    total = pd.merge(f_res, m_res, on=['Nº REMISION', 'FECHA'], how='outer', suffixes=('_f', '_m'))
    total['SALIDA_FINAL'] = total[['FIN_REAL_f', 'FIN_REAL_m']].max(axis=1)

    tiempos = []
    for _, row in total.iterrows():
        llegada, salida = row['FECHA'], row['SALIDA_FINAL']
        dias_rango = pd.date_range(start=llegada.date(), end=salida.date(), freq='D')
        domingos = sum(1 for d in dias_rango if d.weekday() == 6)

        # Horas totales - (24 * domingos)
        horas_puras = (salida - llegada).total_seconds() / 3600
        horas_habiles = horas_puras - (domingos * 24)
        tiempos.append(max(0, horas_habiles))

    return round(sum(tiempos) / len(tiempos), 2)

# 5. DIAGRAMA DE GANTT INTERACTIVO (Parámetros Corregidos)
def graficar_gantt_interactivo(modo):
    if modo == "1":
        fecha = input("Ingrese fecha (AAAA-MM-DD): ").strip()
        df_f = res_fig[res_fig['INICIO_REAL'].dt.strftime('%Y-%m-%d') == fecha].copy()
        df_m = res_mall[res_mall['INICIO_REAL'].dt.strftime('%Y-%m-%d') == fecha].copy()
        titulo = f"Gantt Diario Interactivo - {fecha}"
    else:
        try:
            sem = int(input("Ingrese número de semana: "))
            df_f = res_fig[res_fig['SEMANA'] == sem].copy()
            df_m = res_mall[res_mall['SEMANA'] == sem].copy()
            titulo = f"Gantt Semanal Interactivo - Semana {sem}"
        except: print("⚠️ Semana inválida."); return

    if df_f.empty and df_m.empty:
        print("❌ No hay remisiones procesadas en este periodo."); return

    # Asignar nombres de máquinas para el eje Y
    df_f['Maquina'] = 'FIGURADO'
    df_m['Maquina'] = 'MALLAS'
    df_gantt = pd.concat([df_f, df_m])

    # CORRECCIÓN: Usamos x_start y x_end en lugar de start y end
    fig = px.timeline(
        df_gantt,
        x_start="INICIO_REAL",
        x_end="FIN_REAL",
        y="Maquina",
        color="Nº REMISION",
        title=titulo,
        hover_data=["Nº REMISION", "FECHA_PROMESA"],
        template="plotly_white"
    )

    fig.update_yaxes(autorange="reversed")
    fig.update_layout(showlegend=False, height=450, xaxis_title="Cronograma de Producción")
    fig.show()

# 6. MENÚ DE USUARIO
def menu():
    while True:
        print(f"\n{'='*50}\n GESTIÓN DE TALLER WSPT - INTERACTIVO\n{'='*50}")
        print("1. Rastrear estado de una Remisión")
        print("2. Ver consolidado Semanal (Hechos/Pendientes)")
        print("3. Ver Tiempo de Flujo Promedio (Horas Hábiles)")
        print("4. Generar Diagrama de Gantt Interactivo")
        print("5. Salir")

        op = input("\nSeleccione una opción: ")

        if op == "1":
            n = input("Ingrese el Nº de Remisión: ").strip()
            f = res_fig[res_fig['Nº REMISION'] == n]
            m = res_mall[res_mall['Nº REMISION'] == n]

            if f.empty and m.empty:
                print(f"⚠️ Remisión {n} no encontrada.")
            else:
                f_fin = f['FIN_REAL'].max() if not f.empty else pd.Timestamp.min
                m_fin = m['FIN_REAL'].max() if not m.empty else pd.Timestamp.min
                final = max(f_fin, m_fin)
                promesa = (f.iloc[0] if not f.empty else m.iloc[0])['FECHA_PROMESA']
                print(f"\n--- REPORTE REMISIÓN {n} ---")
                print(f"Estado: {'✅ A TIEMPO' if final <= promesa else '❌ RETRASADO'}")
                print(f"Entrega Estimada: {final.strftime('%Y-%m-%d %H:%M')}")

        elif op == "2":
            sem_f = stat_fig.groupby('Semana').agg({'Hechos': 'sum', 'Pendientes': 'last'})
            sem_m = stat_mall.groupby('Semana').agg({'Hechos': 'sum', 'Pendientes': 'last'})
            consolidado = sem_f.merge(sem_m, on='Semana', suffixes=('_Fig', '_Mall'))
            print("\n--- CONSOLIDADO SEMANAL ---\n", consolidado)

        elif op == "3":
            promedio = calcular_tiempo_flujo_horas_habiles()
            print(f"\n📊 TIEMPO DE FLUJO PROMEDIO: {promedio} Horas Hábiles")
            print("(Descontando periodos de inactividad de los domingos)")

        elif op == "4":
            sub = input("\n¿Desea ver Gantt 1. Diario o 2. Semanal?: ")
            graficar_gantt_interactivo(sub)

        elif op == "5":
            print("Saliendo del sistema..."); break

if __name__ == "__main__":
    menu()

#codigo final
import pandas as pd
import plotly.express as px
from datetime import datetime

# 1. CARGA DE DATOS
archivo = 'datos entrada A dias.xlsx'
df = pd.read_excel(archivo)
df.columns = [c.strip() for c in df.columns]
df['FECHA'] = pd.to_datetime(df['FECHA'])
df['Nº REMISION'] = df['Nº REMISION'].astype(str).str.strip()

# 2. CONFIGURACIÓN DE PROMESA
def calcular_promesa(rj):
    p = rj + pd.Timedelta(days=2)
    if p.weekday() == 6: p += pd.Timedelta(days=1)
    return p.replace(hour=15, minute=0, second=0)

df['FECHA_PROMESA'] = df['FECHA'].apply(calcular_promesa)

# 3. MOTOR DE CÁLCULO WSPT
def procesar_maquina(datos, col_pj):
    df_m = datos[datos[col_pj] > 0].copy()
    df_m['WSPT'] = df_m[col_pj] / df_m['Cant tipos']
    reloj = df_m['FECHA'].min().replace(hour=0, minute=0)
    backlog, finalizados, resumen_diario = pd.DataFrame(), [], []
    hoy = df_m['FECHA'].min()
    ultima_fecha_datos = df_m['FECHA'].max()

    while hoy <= ultima_fecha_datos or not backlog.empty:
        if hoy.weekday() == 6:
            hoy += pd.Timedelta(days=1)
            continue

        pool = pd.concat([backlog, df_m[df_m['FECHA'] == hoy]])
        if not pool.empty:
            pool = pool.sort_values(by=['WSPT', 'Cant tipos'], ascending=[True, False], kind='stable')
            horas_hoy, hechos_hoy, ids_terminados = 0, 0, []
            if reloj < hoy: reloj = hoy

            for idx, row in pool.iterrows():
                pj = row[col_pj]
                if horas_hoy > 0 and (horas_hoy + pj > 24): break

                inicio_tarea = reloj
                reloj += pd.Timedelta(hours=pj)
                horas_hoy += pj
                if reloj.weekday() == 6: reloj += pd.Timedelta(days=1)

                row_copy = row.copy()
                row_copy['INICIO_REAL'] = inicio_tarea
                row_copy['FIN_REAL'] = reloj
                row_copy['SEMANA'] = inicio_tarea.isocalendar()[1]
                finalizados.append(row_copy)
                ids_terminados.append(idx)
                hechos_hoy += 1
                if horas_hoy >= 24: break

            backlog = pool.drop(ids_terminados)
            resumen_diario.append({'Fecha': hoy.date(), 'Semana': hoy.isocalendar()[1],
                                   'Hechos': hechos_hoy, 'Pendientes': len(backlog)})
        hoy += pd.Timedelta(days=1)
        if hoy > ultima_fecha_datos + pd.Timedelta(days=100): break

    return pd.DataFrame(finalizados), pd.DataFrame(resumen_diario)

res_fig, stat_fig = procesar_maquina(df, 'pj fig')
res_mall, stat_mall = procesar_maquina(df, 'pj mall')

# 4. MÉTRICAS DE FLUJO (SIN DOMINGOS)
def calcular_tiempo_flujo_horas_habiles():
    f_res = res_fig[['Nº REMISION', 'FECHA', 'FIN_REAL']]
    m_res = res_mall[['Nº REMISION', 'FECHA', 'FIN_REAL']]
    total = pd.merge(f_res, m_res, on=['Nº REMISION', 'FECHA'], how='outer', suffixes=('_f', '_m'))
    total['SALIDA_FINAL'] = total[['FIN_REAL_f', 'FIN_REAL_m']].max(axis=1)

    tiempos = []
    for _, row in total.iterrows():
        llegada, salida = row['FECHA'], row['SALIDA_FINAL']
        doms = sum(1 for d in pd.date_range(llegada.date(), salida.date(), freq='D') if d.weekday() == 6)
        horas_habiles = ((salida - llegada).total_seconds() / 3600) - (doms * 24)
        tiempos.append(max(0, horas_habiles))
    return round(sum(tiempos) / len(tiempos), 2)

# 5. GANTT INTERACTIVO
def graficar_gantt_interactivo(modo):
    if modo == "1":
        fecha = input("Fecha (AAAA-MM-DD): ").strip()
        df_f = res_fig[res_fig['INICIO_REAL'].dt.strftime('%Y-%m-%d') == fecha].copy()
        df_m = res_mall[res_mall['INICIO_REAL'].dt.strftime('%Y-%m-%d') == fecha].copy()
        titulo = f"Gantt Diario - {fecha}"
    else:
        try:
            sem = int(input("Semana: "))
            df_f = res_fig[res_fig['SEMANA'] == sem].copy()
            df_m = res_mall[res_mall['SEMANA'] == sem].copy()
            titulo = f"Gantt Semanal - Sem {sem}"
        except: return

    df_f['Maquina'], df_m['Maquina'] = 'FIGURADO', 'MALLAS'
    df_gantt = pd.concat([df_f, df_m])

    if df_gantt.empty: print("Sin datos."); return

    fig = px.timeline(df_gantt, x_start="INICIO_REAL", x_end="FIN_REAL", y="Maquina", color="Nº REMISION",
                      title=titulo, hover_data=["Nº REMISION", "FECHA_PROMESA"], template="plotly_white")
    fig.update_yaxes(autorange="reversed")
    fig.update_layout(showlegend=False, height=400)
    fig.show()

# 6. MENÚ
def menu():
    while True:
        print(f"\n{'='*50}\n CONTROL TALLER WSPT\n{'='*50}")
        print("1. Consolidado DIARIO\n2. Consolidado SEMANAL\n3. Flujo Promedio (Horas Hábiles)\n4. Gantt Interactivo\n5. Rastrear Remisión\n6. Salir")

        op = input("\nSeleccione: ")
        if op == "1":
            diario = stat_fig.merge(stat_mall, on='Fecha', suffixes=('_Fig', '_Mall'))
            print("\n--- REPORTE DIARIO ---\n", diario.to_string(index=False))
        elif op == "2":
            sem_f = stat_fig.groupby('Semana').agg({'Hechos': 'sum', 'Pendientes': 'last'})
            sem_m = stat_mall.groupby('Semana').agg({'Hechos': 'sum', 'Pendientes': 'last'})
            print("\n--- REPORTE SEMANAL ---\n", sem_f.merge(sem_m, on='Semana', suffixes=('_Fig', '_Mall')))
        elif op == "3":
            print(f"\n📊 FLUJO PROMEDIO: {calcular_tiempo_flujo_horas_habiles()} HORAS")
        elif op == "4":
            sub = input("1. Diario / 2. Semanal: ")
            graficar_gantt_interactivo(sub)
        elif op == "5":
            n = input("Nº Remisión: ").strip()
            f, m = res_fig[res_fig['Nº REMISION'] == n], res_mall[res_mall['Nº REMISION'] == n]
            if f.empty and m.empty: print("No encontrada."); continue
            salida = max(f['FIN_REAL'].max() if not f.empty else pd.Timestamp.min, m['FIN_REAL'].max() if not m.empty else pd.Timestamp.min)
            print(f"Salida Estimada: {salida}")
        elif op == "6": break

if __name__ == "__main__":
    menu()