# -*- coding: utf-8 -*-
"""Reprosesado mallado 10k .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vUg6s0lE4D1nt-f0B2AWjNeI8Duj2JP
"""

import pandas as pd
import numpy as np
import plotly.express as px
from datetime import datetime

# ==========================================
# 1. CARGA DE DATOS Y PARAMETROS
# ==========================================
archivo = 'datos entrada A dias.xlsx'
try:
    df = pd.read_excel(archivo)
except FileNotFoundError:
    print(f"Error: No se encontro el archivo '{archivo}'.")
    exit()

df.columns = [c.strip() for c in df.columns]
df['FECHA'] = pd.to_datetime(df['FECHA'])
df['Nº REMISION'] = df['Nº REMISION'].astype(str).str.strip()

# W_j: Importancia segun cantidad de tipos de producto
df['W_j'] = df['Cant tipos'].fillna(1).replace(0, 1)

# ==========================================
# 2. FECHAS DE ENTREGA d_j
# ==========================================
def calcular_promesa(rj):
    # Promesa: 2 dias despues a las 15:00. Domingos no cuentan.
    p = rj + pd.Timedelta(days=2)
    if p.weekday() == 6:
        p += pd.Timedelta(days=1)
    return p.replace(hour=15, minute=0, second=0)

df['FECHA_PROMESA'] = df['FECHA'].apply(calcular_promesa)
# Identificar la semana del ano
df['SEMANA_ISO'] = df['FECHA'].dt.isocalendar().week

# ==========================================
# 3. MOTORES DE SECUENCIACION ESTATICA
# ==========================================
def agregar_horas_habiles(fecha_inicio, horas):
    actual = fecha_inicio
    restante = horas
    while restante > 0:
        if actual.weekday() == 6: # Es domingo, saltar
            actual += pd.Timedelta(days=1)
            actual = actual.replace(hour=0, minute=0, second=0)

        dias_para_domingo = 6 - actual.weekday()
        proximo_domingo = (actual + pd.Timedelta(days=dias_para_domingo)).replace(hour=0, minute=0, second=0)
        horas_al_domingo = (proximo_domingo - actual).total_seconds() / 3600.0

        if restante <= horas_al_domingo:
            actual += pd.Timedelta(hours=restante)
            restante = 0
        else:
            actual = proximo_domingo + pd.Timedelta(days=1)
            restante -= horas_al_domingo
    return actual

def aplicar_regla_ordenamiento(df_m, col_pj, regla):
    if regla == 'FCFS': df_m = df_m.sort_values(by='FECHA')
    elif regla == 'SPT': df_m = df_m.sort_values(by=col_pj)
    elif regla == 'WSPT':
        df_m['PRIO'] = df_m[col_pj] / df_m['W_j']
        df_m = df_m.sort_values(by='PRIO')
    elif regla == 'LPT': df_m = df_m.sort_values(by=col_pj, ascending=False)
    elif regla == 'EDD': df_m = df_m.sort_values(by='d_j_horas')
    elif regla == 'MST':
        df_m['PRIO'] = df_m['d_j_horas'] - df_m[col_pj]
        df_m = df_m.sort_values(by='PRIO')
    elif regla == 'CR':
        df_m['PRIO'] = df_m['d_j_horas'] / df_m[col_pj]
        df_m = df_m.sort_values(by='PRIO')
    elif regla == 'WLPT':
        df_m['PRIO'] = df_m[col_pj] * df_m['W_j']
        df_m = df_m.sort_values(by='PRIO', ascending=False)
    return df_m

# --- MOTOR 1: PROGRAMACION SEMANAL ---
def procesar_semana_estatica(df_semana, col_pj, regla):
    df_m = df_semana[df_semana[col_pj] > 0].copy()
    if df_m.empty: return []

    inicio_semana = df_m['FECHA'].min() - pd.Timedelta(days=df_m['FECHA'].min().weekday())
    inicio_semana = inicio_semana.replace(hour=0, minute=0, second=0)
    df_m['d_j_horas'] = (df_m['FECHA_PROMESA'] - inicio_semana).dt.total_seconds() / 3600.0

    df_m = aplicar_regla_ordenamiento(df_m, col_pj, regla)

    finalizados = []
    reloj = inicio_semana

    for _, row in df_m.iterrows():
        if reloj < row['FECHA']: reloj = row['FECHA'].replace(hour=0, minute=0, second=0)
        if reloj.weekday() == 6:
            reloj += pd.Timedelta(days=1)
            reloj = reloj.replace(hour=0, minute=0, second=0)

        inicio_tarea = reloj
        reloj = agregar_horas_habiles(reloj, row[col_pj])

        row_copy = row.copy()
        row_copy['INICIO_REAL'] = inicio_tarea
        row_copy['FIN_REAL'] = reloj
        row_copy['C_j_horas'] = (reloj - row_copy['FECHA']).total_seconds() / 3600.0
        finalizados.append(row_copy)
    return finalizados

# --- MOTOR 2: PROGRAMACION DIARIA ---
def procesar_dia_estatico(df_dia, col_pj, regla, reloj_global):
    df_m = df_dia[df_dia[col_pj] > 0].copy()
    if df_m.empty: return [], reloj_global

    inicio_dia = df_m['FECHA'].min().replace(hour=0, minute=0, second=0)
    df_m['d_j_horas'] = (df_m['FECHA_PROMESA'] - inicio_dia).dt.total_seconds() / 3600.0

    df_m = aplicar_regla_ordenamiento(df_m, col_pj, regla)

    finalizados = []
    # El reloj arranca en la hora en la que termino el dia anterior o al inicio del dia actual
    reloj = max(reloj_global, inicio_dia)

    for _, row in df_m.iterrows():
        if reloj < row['FECHA']: reloj = row['FECHA'].replace(hour=0, minute=0, second=0)
        if reloj.weekday() == 6:
            reloj += pd.Timedelta(days=1)
            reloj = reloj.replace(hour=0, minute=0, second=0)

        inicio_tarea = reloj
        reloj = agregar_horas_habiles(reloj, row[col_pj])

        row_copy = row.copy()
        row_copy['INICIO_REAL'] = inicio_tarea
        row_copy['FIN_REAL'] = reloj
        row_copy['C_j_horas'] = (reloj - row_copy['FECHA']).total_seconds() / 3600.0
        finalizados.append(row_copy)

    return finalizados, reloj

# ==========================================
# 4. EVALUACION GLOBAL DE REGLAS
# ==========================================
def calcular_objetivos(df_resultados):
    if df_resultados.empty: return 0, 0, 0
    df_resultados['T_j'] = np.maximum(0, (df_resultados['FIN_REAL'] - df_resultados['FECHA_PROMESA']).dt.total_seconds() / 3600.0)
    df_resultados['U_j'] = (df_resultados['T_j'] > 0).astype(int)

    sum_Wj_Cj = np.sum(df_resultados['W_j'] * df_resultados['C_j_horas'])
    sum_Wj_Tj = np.sum(df_resultados['W_j'] * df_resultados['T_j'])
    sum_Uj = np.sum(df_resultados['U_j'])
    return sum_Wj_Cj, sum_Wj_Tj, sum_Uj

def evaluar_regla_semanal(regla):
    res_fig, res_mall = [], []
    for sem in df['SEMANA_ISO'].unique():
        df_sem = df[df['SEMANA_ISO'] == sem]
        res_fig.extend(procesar_semana_estatica(df_sem, 'pj fig', regla))
        res_mall.extend(procesar_semana_estatica(df_sem, 'pj mall', regla))
    return pd.DataFrame(res_fig), pd.DataFrame(res_mall)

def evaluar_regla_diaria(regla):
    res_fig, res_mall = [], []
    reloj_fig = pd.Timestamp.min
    reloj_mall = pd.Timestamp.min

    # Procesar dia a dia secuencialmente
    dias = df['FECHA'].dt.date.unique()
    dias.sort()

    for dia in dias:
        df_dia = df[df['FECHA'].dt.date == dia]

        fig_terminados, reloj_fig = procesar_dia_estatico(df_dia, 'pj fig', regla, reloj_fig)
        mall_terminados, reloj_mall = procesar_dia_estatico(df_dia, 'pj mall', regla, reloj_mall)

        res_fig.extend(fig_terminados)
        res_mall.extend(mall_terminados)

    return pd.DataFrame(res_fig), pd.DataFrame(res_mall)

# Variables globales para el Gantt
res_fig_actual, res_mall_actual = pd.DataFrame(), pd.DataFrame()
regla_actual = "WSPT"

# ==========================================
# 5. DIAGRAMA DE GANTT (PLOTLY)
# ==========================================
def graficar_gantt_interactivo(modo):
    if res_fig_actual.empty and res_mall_actual.empty:
        print("Debe ejecutar una regla primero.")
        return

    if modo == "1":
        fecha = input("Ingrese fecha (AAAA-MM-DD): ").strip()
        df_f = res_fig_actual[res_fig_actual['INICIO_REAL'].dt.strftime('%Y-%m-%d') == fecha].copy()
        df_m = res_mall_actual[res_mall_actual['INICIO_REAL'].dt.strftime('%Y-%m-%d') == fecha].copy()
        titulo = f"Gantt Diario Estatico ({regla_actual}) - {fecha}"
    else:
        try:
            sem = int(input("Ingrese numero de semana (ej. 1, 2, 3...): "))
            df_f = res_fig_actual[res_fig_actual['SEMANA_ISO'] == sem].copy()
            df_m = res_mall_actual[res_mall_actual['SEMANA_ISO'] == sem].copy()
            titulo = f"Gantt Semanal Estatico ({regla_actual}) - Semana {sem}"
        except:
            print("Semana invalida.")
            return

    if df_f.empty and df_m.empty:
        print("No hay remisiones en este periodo.")
        return

    df_f['Maquina'] = 'FIGURADO'
    df_m['Maquina'] = 'MALLAS'
    df_gantt = pd.concat([df_f, df_m])

    fig = px.timeline(
        df_gantt, x_start="INICIO_REAL", x_end="FIN_REAL",
        y="Maquina", color="Nº REMISION", title=titulo,
        hover_data=["Nº REMISION", "FECHA_PROMESA"],
        template="plotly_white"
    )
    fig.update_yaxes(autorange="reversed")
    fig.update_layout(showlegend=False, height=450, xaxis_title="Cronograma")
    fig.show()

# ==========================================
# 6. MENU PRINCIPAL
# ==========================================
def menu():
    global res_fig_actual, res_mall_actual, regla_actual

    # Cargar datos por defecto
    res_fig_actual, res_mall_actual = evaluar_regla_semanal(regla_actual)

    while True:
        print(f"\n{'='*75}\n TALLER 1 - SOLUCION PUNTO D (ESTATICO)\n{'='*75}")
        print(f"Regla Activa en Memoria: {regla_actual}")
        print("1. Rastrear estado de una Remision (Regla Activa)")
        print("2. Generar Diagrama de Gantt Interactivo (Regla Activa)")
        print("3. Comparar 8 reglas CONSOLIDADO TOTAL")
        print("4. Comparar 8 reglas SEMANAL (Detalle por Semana)")
        print("5. Comparar 8 reglas DIARIA  (Detalle por Dia)")
        print("6. Cambiar Regla Activa (FCFS, SPT, WSPT, LPT, EDD, MST, CR, WLPT)")
        print("7. Salir")

        op = input("\nSeleccione una opcion: ")

        if op == "1":
            n = input("Ingrese el Nº de Remision: ").strip()
            f = res_fig_actual[res_fig_actual['Nº REMISION'] == n]
            m = res_mall_actual[res_mall_actual['Nº REMISION'] == n]

            if f.empty and m.empty:
                print(f"Remision {n} no encontrada.")
            else:
                f_fin = f['FIN_REAL'].max() if not f.empty else pd.Timestamp.min
                m_fin = m['FIN_REAL'].max() if not m.empty else pd.Timestamp.min
                final = max(f_fin, m_fin)
                promesa = (f.iloc[0] if not f.empty else m.iloc[0])['FECHA_PROMESA']

                print(f"\n--- REPORTE REMISION {n} ---")
                print(f"Entrega Prometida: {promesa.strftime('%Y-%m-%d %H:%M')}")
                print(f"Terminacion Real:  {final.strftime('%Y-%m-%d %H:%M')}")
                print(f"Estado: {'A TIEMPO' if final <= promesa else 'RETRASADO'}")

        elif op == "2":
            sub = input("\nDesea ver Gantt 1. Diario o 2. Semanal?: ")
            graficar_gantt_interactivo(sub)

        elif op == "3":
            reglas = ['FCFS', 'SPT', 'WSPT', 'LPT', 'EDD', 'MST', 'CR', 'WLPT']
            resultados = []
            print("\nCalculando Consolidado Total de las 8 reglas...")

            for r in reglas:
                df_f, df_m = evaluar_regla_semanal(r)
                df_total = pd.concat([df_f, df_m])
                wC, wT, U = calcular_objetivos(df_total)
                resultados.append({'Regla': r, 'Suma_Wj_Cj': wC, 'Suma_Wj_Tj': wT, 'Total_Uj': U})

            df_resumen = pd.DataFrame(resultados)
            print("\n--- COMPARATIVA CONSOLIDADA TOTAL (8 REGLAS ESTATICAS) ---")
            print(df_resumen.to_string(index=False, float_format="%.2f"))

        elif op == "4":
            reglas = ['FCFS', 'SPT', 'WSPT', 'LPT', 'EDD', 'MST', 'CR', 'WLPT']
            resultados = []
            print("\nCalculando las 8 reglas estaticas agrupando lotes SEMANALMENTE...")

            for r in reglas:
                df_f, df_m = evaluar_regla_semanal(r)
                df_total = pd.concat([df_f, df_m])

                # Desglose por semana
                for sem in sorted(df_total['SEMANA_ISO'].unique()):
                    df_sem = df_total[df_total['SEMANA_ISO'] == sem].copy()
                    wC, wT, U = calcular_objetivos(df_sem)
                    resultados.append({'Regla': r, 'Periodo': f"Semana {sem}", 'Wj_Cj': wC, 'Wj_Tj': wT, 'Uj': U})

                # Consolidado total de la regla
                wC_t, wT_t, U_t = calcular_objetivos(df_total)
                resultados.append({'Regla': f"[{r}]", 'Periodo': 'TOTAL', 'Wj_Cj': wC_t, 'Wj_Tj': wT_t, 'Uj': U_t})
                resultados.append({'Regla': '-'*6, 'Periodo': '-'*10, 'Wj_Cj': float('nan'), 'Wj_Tj': float('nan'), 'Uj': float('nan')})

            df_resumen = pd.DataFrame(resultados).dropna()
            print("\n--- COMPARATIVA SEMANAL (8 REGLAS ESTATICAS) ---")
            print(df_resumen.to_string(index=False, float_format="%.2f"))

        elif op == "5":
            reglas = ['FCFS', 'SPT', 'WSPT', 'LPT', 'EDD', 'MST', 'CR', 'WLPT']
            resultados = []
            print("\nCalculando las 8 reglas estaticas agrupando lotes DIARIAMENTE...")

            for r in reglas:
                df_f, df_m = evaluar_regla_diaria(r)
                df_total = pd.concat([df_f, df_m])

                # Desglose por Dia
                for dia in sorted(df_total['FECHA'].dt.date.unique()):
                    df_dia = df_total[df_total['FECHA'].dt.date == dia].copy()
                    wC, wT, U = calcular_objetivos(df_dia)
                    resultados.append({'Regla': r, 'Periodo': str(dia), 'Wj_Cj': wC, 'Wj_Tj': wT, 'Uj': U})

                # Consolidado total de la regla
                wC_t, wT_t, U_t = calcular_objetivos(df_total)
                resultados.append({'Regla': f"[{r}]", 'Periodo': 'TOTAL', 'Wj_Cj': wC_t, 'Wj_Tj': wT_t, 'Uj': U_t})
                resultados.append({'Regla': '-'*6, 'Periodo': '-'*10, 'Wj_Cj': float('nan'), 'Wj_Tj': float('nan'), 'Uj': float('nan')})

            df_resumen = pd.DataFrame(resultados).dropna()
            print("\n--- COMPARATIVA DIARIA (8 REGLAS ESTATICAS) ---")
            # Configurar para imprimir todos los dias sin ocultar filas medias
            with pd.option_context('display.max_rows', None, 'display.max_columns', None):
                print(df_resumen.to_string(index=False, float_format="%.2f"))

        elif op == "6":
            print("\nReglas estaticas disponibles:")
            print("1:FCFS | 2:SPT | 3:WSPT | 4:LPT | 5:EDD | 6:MST | 7:CR | 8:WLPT")
            sel = input("Seleccione regla (1-8): ").strip()
            mapa = {'1': 'FCFS', '2': 'SPT', '3': 'WSPT', '4': 'LPT',
                    '5': 'EDD', '6': 'MST', '7': 'CR', '8': 'WLPT'}
            if sel in mapa:
                regla_actual = mapa[sel]
                print(f"Procesando programacion semanal con {regla_actual}...")
                res_fig_actual, res_mall_actual = evaluar_regla_semanal(regla_actual)
                print("Calculo completado. Diagramas y rastreo actualizados.")
            else:
                print("Opcion no valida.")

        elif op == "7":
            print("Saliendo...")
            break

if __name__ == "__main__":
    menu()

import pandas as pd
import numpy as np
import plotly.express as px
from datetime import datetime

# ==========================================
# 1. CARGA DE DATOS Y PARAMETROS (Footnote 2)
# ==========================================
archivo = 'datos entrada A dias.xlsx'
try:
    df = pd.read_excel(archivo)
except FileNotFoundError:
    print(f"Error: No se encontro el archivo '{archivo}'.")
    exit()

df.columns = [c.strip() for c in df.columns]
df['FECHA'] = pd.to_datetime(df['FECHA'])
df['Nº REMISION'] = df['Nº REMISION'].astype(str).str.strip()

# W_j: Importancia (1, 2 o 3 tipos de producto)
df['W_j'] = df['Cant tipos'].fillna(1).replace(0, 1)

# ==========================================
# 2. FECHAS DE ENTREGA d_j (Footnote 3)
# ==========================================
def calcular_promesa(rj):
    # Promesa: 2 dias despues a las 3:00 pm. Domingos no cuentan.
    p = rj + pd.Timedelta(days=2)
    if p.weekday() == 6:
        p += pd.Timedelta(days=1)
    return p.replace(hour=15, minute=0, second=0)

df['FECHA_PROMESA'] = df['FECHA'].apply(calcular_promesa)
# Extraer la semana para la "programacion semanal" exigida
df['SEMANA_ISO'] = df['FECHA'].dt.isocalendar().week

# ==========================================
# 3. MOTOR DINAMICO (Actualizacion Lote=5)
# ==========================================
def agregar_horas_habiles(fecha_inicio, horas):
    actual = fecha_inicio
    restante = horas
    while restante > 0:
        if actual.weekday() == 6: # Es domingo, saltar
            actual += pd.Timedelta(days=1)
            actual = actual.replace(hour=0, minute=0, second=0)

        dias_para_domingo = 6 - actual.weekday()
        proximo_domingo = (actual + pd.Timedelta(days=dias_para_domingo)).replace(hour=0, minute=0, second=0)
        horas_al_domingo = (proximo_domingo - actual).total_seconds() / 3600.0

        if restante <= horas_al_domingo:
            actual += pd.Timedelta(hours=restante)
            restante = 0
        else:
            actual = proximo_domingo + pd.Timedelta(days=1)
            restante -= horas_al_domingo
    return actual

def procesar_semana_dinamica(df_semana, col_pj, regla, batch_size=5):
    df_m = df_semana[df_semana[col_pj] > 0].copy()
    if df_m.empty: return []

    # El reloj inicia el lunes a las 00:00 de esa semana
    reloj = df_m['FECHA'].min() - pd.Timedelta(days=df_m['FECHA'].min().weekday())
    reloj = reloj.replace(hour=0, minute=0, second=0)

    finalizados = []
    unscheduled = df_m.copy()

    while not unscheduled.empty:
        if reloj.weekday() == 6:
            reloj += pd.Timedelta(days=1)
            reloj = reloj.replace(hour=0, minute=0, second=0)

        disp = unscheduled[unscheduled['FECHA'] <= reloj].copy()

        if disp.empty:
            reloj = unscheduled['FECHA'].min()
            continue

        # --- REGLAS DINAMICAS ---
        dj_minus_t = (disp['FECHA_PROMESA'] - reloj).dt.total_seconds() / 3600.0
        pj = disp[col_pj]
        wj = disp['W_j']

        if regla == 'CR':
            disp['PRIORIDAD'] = dj_minus_t / pj
            asc = True
        elif regla == 'MST':
            disp['PRIORIDAD'] = dj_minus_t - pj
            asc = True
        elif regla == 'ATC':
            K = 2.0
            p_avg = max(pj.mean(), 1e-5)
            slack = np.maximum(0, dj_minus_t - pj)
            disp['PRIORIDAD'] = (wj / pj) * np.exp(-slack / (K * p_avg))
            asc = False
        elif regla == 'COVERT':
            K = 2.0
            p_avg = max(pj.mean(), 1e-5)
            slack = np.maximum(0, dj_minus_t - pj)
            cov_factor = np.maximum(0, 1 - (slack / (K * p_avg)))
            disp['PRIORIDAD'] = (wj / pj) * cov_factor
            asc = False
        elif regla == 'RSI':
            slack = dj_minus_t - pj
            time_to_due = np.maximum(1e-5, dj_minus_t)
            disp['PRIORIDAD'] = slack / time_to_due
            asc = True

        disp = disp.sort_values(by=['PRIORIDAD', 'W_j'], ascending=[asc, False], kind='stable')
        batch = disp.head(batch_size) # Actualizacion cada 5 trabajos

        for idx, row in batch.iterrows():
            if reloj.weekday() == 6:
                reloj += pd.Timedelta(days=1)
                reloj = reloj.replace(hour=0, minute=0, second=0)

            inicio_tarea = reloj
            reloj = agregar_horas_habiles(reloj, row[col_pj])

            row_copy = row.copy()
            row_copy['INICIO_REAL'] = inicio_tarea
            row_copy['FIN_REAL'] = reloj
            row_copy['C_j_horas'] = (reloj - row_copy['FECHA']).total_seconds() / 3600.0

            finalizados.append(row_copy)
            unscheduled = unscheduled.drop(idx)

    return finalizados

# ==========================================
# 4. EVALUACION DE LOS 3 OBJETIVOS DEL TALLER
# ==========================================
def calcular_objetivos_punto_e(df_resultados):
    if df_resultados.empty: return 0, 0, 0

    # Tardanza (T_j) en horas
    df_resultados['T_j'] = np.maximum(0, (df_resultados['FIN_REAL'] - df_resultados['FECHA_PROMESA']).dt.total_seconds() / 3600.0)
    # Trabajo tardio binario (U_j)
    df_resultados['U_j'] = (df_resultados['T_j'] > 0).astype(int)

    sum_Wj_Cj = np.sum(df_resultados['W_j'] * df_resultados['C_j_horas'])
    sum_Wj_Tj = np.sum(df_resultados['W_j'] * df_resultados['T_j'])
    sum_Uj = np.sum(df_resultados['U_j'])

    return sum_Wj_Cj, sum_Wj_Tj, sum_Uj

def evaluar_regla_completa(regla):
    resultados_fig = []
    resultados_mall = []
    semanas = df['SEMANA_ISO'].unique()

    # Programacion Semanal (como exige el PDF)
    for sem in semanas:
        df_sem = df[df['SEMANA_ISO'] == sem]
        resultados_fig.extend(procesar_semana_dinamica(df_sem, 'pj fig', regla))
        resultados_mall.extend(procesar_semana_dinamica(df_sem, 'pj mall', regla))

    df_fig = pd.DataFrame(resultados_fig)
    df_mall = pd.DataFrame(resultados_mall)

    return df_fig, df_mall

# Variables en memoria para Gantt
res_fig_actual, res_mall_actual = pd.DataFrame(), pd.DataFrame()
regla_actual = "CR"

# ==========================================
# 5. DIAGRAMA DE GANTT (PLOTLY)
# ==========================================
def graficar_gantt_interactivo(modo):
    if res_fig_actual.empty and res_mall_actual.empty:
        print("Debe ejecutar una regla primero (Opcion 5).")
        return

    if modo == "1":
        fecha = input("Ingrese fecha (AAAA-MM-DD): ").strip()
        df_f = res_fig_actual[res_fig_actual['INICIO_REAL'].dt.strftime('%Y-%m-%d') == fecha].copy()
        df_m = res_mall_actual[res_mall_actual['INICIO_REAL'].dt.strftime('%Y-%m-%d') == fecha].copy()
        titulo = f"Gantt Diario Dinamico ({regla_actual}) - {fecha}"
    else:
        try:
            sem = int(input("Ingrese numero de semana (ej. 1, 2, 3...): "))
            df_f = res_fig_actual[res_fig_actual['SEMANA_ISO'] == sem].copy()
            df_m = res_mall_actual[res_mall_actual['SEMANA_ISO'] == sem].copy()
            titulo = f"Gantt Semanal Dinamico ({regla_actual}) - Semana {sem}"
        except:
            print("Semana invalida.")
            return

    if df_f.empty and df_m.empty:
        print("No hay remisiones en este periodo.")
        return

    df_f['Maquina'] = 'FIGURADO'
    df_m['Maquina'] = 'MALLAS'
    df_gantt = pd.concat([df_f, df_m])

    fig = px.timeline(
        df_gantt, x_start="INICIO_REAL", x_end="FIN_REAL",
        y="Maquina", color="Nº REMISION", title=titulo,
        hover_data=["Nº REMISION", "FECHA_PROMESA", "PRIORIDAD"],
        template="plotly_white"
    )
    fig.update_yaxes(autorange="reversed")
    fig.update_layout(showlegend=False, height=450, xaxis_title="Cronograma")
    fig.show()

# ==========================================
# 6. MENU PRINCIPAL
# ==========================================
def menu():
    global res_fig_actual, res_mall_actual, regla_actual

    # Cargar datos por defecto
    res_fig_actual, res_mall_actual = evaluar_regla_completa(regla_actual)

    while True:
        print(f"\n{'='*70}\n TALLER 1 - SOLUCION PUNTO E (DINAMICO LOTE=5)\n{'='*70}")
        print(f"Regla Activa en Memoria: {regla_actual}")
        print("1. Rastrear estado de una Remision (Regla Activa)")
        print("2. Generar Diagrama de Gantt Interactivo (Regla Activa)")
        print("3. Comparar 5 reglas CONSOLIDADO TOTAL")
        print("4. Comparar 5 reglas SEMANAL (Detalle por Semana)")
        print("5. Cambiar Regla Activa (CR, MST, ATC, COVERT, RSI)")
        print("6. Salir")

        op = input("\nSeleccione una opcion: ")

        if op == "1":
            n = input("Ingrese el Nº de Remision: ").strip()
            f = res_fig_actual[res_fig_actual['Nº REMISION'] == n]
            m = res_mall_actual[res_mall_actual['Nº REMISION'] == n]

            if f.empty and m.empty:
                print(f"Remision {n} no encontrada.")
            else:
                f_fin = f['FIN_REAL'].max() if not f.empty else pd.Timestamp.min
                m_fin = m['FIN_REAL'].max() if not m.empty else pd.Timestamp.min
                final = max(f_fin, m_fin)
                promesa = (f.iloc[0] if not f.empty else m.iloc[0])['FECHA_PROMESA']

                print(f"\n--- REPORTE REMISION {n} ---")
                print(f"Entrega Prometida: {promesa.strftime('%Y-%m-%d %H:%M')}")
                print(f"Terminacion Real:  {final.strftime('%Y-%m-%d %H:%M')}")
                print(f"Estado: {'A TIEMPO' if final <= promesa else 'RETRASADO'}")

        elif op == "2":
            sub = input("\nDesea ver Gantt 1. Diario o 2. Semanal?: ")
            graficar_gantt_interactivo(sub)

        elif op == "3":
            reglas = ['CR', 'MST', 'ATC', 'COVERT', 'RSI']
            resultados = []
            print("\nCalculando Consolidado Total de las 5 reglas dinamicas...")

            for r in reglas:
                df_f, df_m = evaluar_regla_completa(r)
                df_total = pd.concat([df_f, df_m])
                wC, wT, U = calcular_objetivos_punto_e(df_total)
                resultados.append({'Regla': r, 'Suma_Wj_Cj': wC, 'Suma_Wj_Tj': wT, 'Total_Uj': U})

            df_resumen = pd.DataFrame(resultados)
            print("\n--- COMPARATIVA CONSOLIDADA TOTAL (5 REGLAS DINAMICAS) ---")
            print(df_resumen.to_string(index=False, float_format="%.2f"))
            print("-" * 65)

        elif op == "4":
            reglas = ['CR', 'MST', 'ATC', 'COVERT', 'RSI']
            resultados = []
            print("\nCalculando las 5 reglas dinamicas con desglose SEMANAL...")

            for r in reglas:
                df_f, df_m = evaluar_regla_completa(r)
                df_total = pd.concat([df_f, df_m])

                # Desglose por semana
                for sem in sorted(df_total['SEMANA_ISO'].unique()):
                    df_sem = df_total[df_total['SEMANA_ISO'] == sem].copy()
                    wC, wT, U = calcular_objetivos_punto_e(df_sem)
                    resultados.append({'Regla': r, 'Periodo': f"Semana {sem}", 'Wj_Cj': wC, 'Wj_Tj': wT, 'Uj': U})

                # Consolidado total de la regla
                wC_t, wT_t, U_t = calcular_objetivos_punto_e(df_total)
                resultados.append({'Regla': f"[{r}]", 'Periodo': 'TOTAL', 'Wj_Cj': wC_t, 'Wj_Tj': wT_t, 'Uj': U_t})
                resultados.append({'Regla': '-'*6, 'Periodo': '-'*10, 'Wj_Cj': float('nan'), 'Wj_Tj': float('nan'), 'Uj': float('nan')})

            df_resumen = pd.DataFrame(resultados).dropna()
            print("\n--- COMPARATIVA SEMANAL (5 REGLAS DINAMICAS) ---")
            print(df_resumen.to_string(index=False, float_format="%.2f"))

        elif op == "5":
            print("\nReglas dinamicas:")
            print("1. CR | 2. MST | 3. ATC | 4. COVERT | 5. RSI")
            sel = input("Seleccione regla (1-5): ").strip()
            mapa = {'1': 'CR', '2': 'MST', '3': 'ATC', '4': 'COVERT', '5': 'RSI'}
            if sel in mapa:
                regla_actual = mapa[sel]
                print(f"Procesando programacion semanal con {regla_actual}...")
                res_fig_actual, res_mall_actual = evaluar_regla_completa(regla_actual)
                print("Calculo completado. Diagramas y rastreo actualizados.")
            else:
                print("Opcion no valida.")

        elif op == "6":
            print("Saliendo...")
            break

if __name__ == "__main__":
    menu()