# -*- coding: utf-8 -*-
"""Trabajo aplicado de 10k Presentación PCP .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1crjgTu5KvfsJ8BFgcpya2PtzzljQn7JG
"""

# =================================================================
#  EJERCICIO A PARA MINIMIZAR FLUJO (WSPT)
# =================================================================
import pandas as pd
import plotly.express as px
from datetime import datetime
import requests
import io

# 1. CARGA DE DATOS DESDE GITHUB
url_github = "https://github.com/Fev23/Datos-entrada-Taller-Plan-Eduyn/raw/refs/heads/main/datos%20entrada%20A%20dias.xlsx"

try:
    response = requests.get(url_github)
    response.raise_for_status()
    df = pd.read_excel(io.BytesIO(response.content))
    print(" =) Los datos fueron cargados correctamente desde GitHub. =) ")
except Exception as e:
    print(f" Error al conectar con GitHub: {e}")
    df = pd.read_excel('datos entrada A dias.xlsx')

# Limpieza inicial
df.columns = [c.strip() for c in df.columns]
df['FECHA'] = pd.to_datetime(df['FECHA'])
df['Nº REMISION'] = df['Nº REMISION'].astype(str).str.strip()

# 2. CONFIGURACIÓN DE PROMESA
def calcular_promesa(rj):
    p = rj + pd.Timedelta(days=2)
    if p.weekday() == 6: p += pd.Timedelta(days=1)
    return p.replace(hour=15, minute=0, second=0)

df['FECHA_PROMESA'] = df['FECHA'].apply(calcular_promesa)

# 3. MOTOR DE CÁLCULO WSPT
def procesar_maquina(datos, col_pj):
    df_m = datos[datos[col_pj] > 0].copy()
    df_m['WSPT'] = df_m[col_pj] / df_m['Cant tipos']
    reloj = df_m['FECHA'].min().replace(hour=0, minute=0)
    backlog, finalizados, resumen_diario = pd.DataFrame(), [], []
    hoy = df_m['FECHA'].min()
    ultima_fecha_datos = df_m['FECHA'].max()

    while hoy <= ultima_fecha_datos or not backlog.empty:
        if hoy.weekday() == 6:
            hoy += pd.Timedelta(days=1)
            continue

        pool = pd.concat([backlog, df_m[df_m['FECHA'] == hoy]])
        if not pool.empty:
            pool = pool.sort_values(by=['WSPT', 'Cant tipos'], ascending=[True, False], kind='stable')
            horas_hoy, hechos_hoy, ids_terminados = 0, 0, []
            if reloj < hoy: reloj = hoy

            for idx, row in pool.iterrows():
                pj = row[col_pj]
                if horas_hoy > 0 and (horas_hoy + pj > 24): break

                inicio_tarea = reloj
                reloj += pd.Timedelta(hours=pj)
                horas_hoy += pj
                if reloj.weekday() == 6: reloj += pd.Timedelta(days=1)

                row_copy = row.copy()
                row_copy['INICIO_REAL'] = inicio_tarea
                row_copy['FIN_REAL'] = reloj
                row_copy['SEMANA'] = inicio_tarea.isocalendar()[1]
                finalizados.append(row_copy)
                ids_terminados.append(idx)
                hechos_hoy += 1
                if horas_hoy >= 24: break

            backlog = pool.drop(ids_terminados)
            resumen_diario.append({'Fecha': hoy.date(), 'Hechos': hechos_hoy, 'Pendientes': len(backlog), 'Semana': hoy.isocalendar()[1]})

        hoy += pd.Timedelta(days=1)
        if hoy > ultima_fecha_datos + pd.Timedelta(days=100): break

    return pd.DataFrame(finalizados), pd.DataFrame(resumen_diario)

res_fig, stat_fig = procesar_maquina(df, 'pj fig')
res_mall, stat_mall = procesar_maquina(df, 'pj mall')

# 4. FUNCIONES DE APOYO Y KPIs
def calcular_tiempo_flujo():
    f_res = res_fig[['Nº REMISION', 'FECHA', 'FIN_REAL']]
    m_res = res_mall[['Nº REMISION', 'FECHA', 'FIN_REAL']]
    total = pd.merge(f_res, m_res, on=['Nº REMISION', 'FECHA'], how='outer', suffixes=('_f', '_m'))
    total['SALIDA_FINAL'] = total[['FIN_REAL_f', 'FIN_REAL_m']].max(axis=1)

    tiempos = []
    for _, row in total.iterrows():
        llegada, salida = row['FECHA'], row['SALIDA_FINAL']
        doms = sum(1 for d in pd.date_range(llegada.date(), salida.date(), freq='D') if d.weekday() == 6)
        horas_habiles = ((salida - llegada).total_seconds() / 3600) - (doms * 24)
        tiempos.append(max(0, horas_habiles))
    return round(sum(tiempos) / len(tiempos), 2)

def calcular_indicadores():
    f_res, m_res = res_fig[['Nº REMISION', 'FECHA_PROMESA', 'FIN_REAL']], res_mall[['Nº REMISION', 'FECHA_PROMESA', 'FIN_REAL']]
    total = pd.merge(f_res, m_res, on=['Nº REMISION'], how='outer', suffixes=('_f', '_m'))
    total['SALIDA_MAX'] = total[['FIN_REAL_f', 'FIN_REAL_m']].max(axis=1)
    total['PROMESA'] = total['FECHA_PROMESA_f'].fillna(total['FECHA_PROMESA_m'])

    # Nivel de servicio (OTD)
    nivel_servicio = ( (total['SALIDA_MAX'] <= total['PROMESA']).mean() * 100 ).round(2)
    total['RETRASO'] = (total['SALIDA_MAX'] - total['PROMESA']).dt.total_seconds() / 3600
    tardanza = total[total['RETRASO'] > 0]['RETRASO'].mean()

    # Utilización
    uso_f = (res_fig['pj fig'].sum() / (len(stat_fig) * 24) * 100).round(1)
    uso_m = (res_mall['pj mall'].sum() / (len(stat_mall) * 24) * 100).round(1)

    print(f"\n{' DASHBOARD DE DESEMPEÑO ':^50}")
    print("-" * 50)
    print(f"OTD (Nivel de Servicio): {nivel_servicio}%")
    print(f"Tardanza Promedio:       {round(tardanza, 1) if not pd.isna(tardanza) else 0} Horas")
    print(f"Utilización Figurado:    {uso_f}%")
    print(f"Utilización Mallas:      {uso_m}%")
    print("-" * 50)

def reporte_retrasos():
    f_res, m_res = res_fig[['Nº REMISION', 'FECHA_PROMESA', 'FIN_REAL']], res_mall[['Nº REMISION', 'FECHA_PROMESA', 'FIN_REAL']]
    total = pd.merge(f_res, m_res, on=['Nº REMISION'], how='outer')
    total['SALIDA'] = total[['FIN_REAL_x', 'FIN_REAL_y']].max(axis=1)
    total['PROMESA'] = total['FECHA_PROMESA_x'].fillna(total['FECHA_PROMESA_y'])

    retrasos = total[total['SALIDA'] > total['PROMESA']].copy()
    if retrasos.empty:
        print("\n No hay pedidos retrasados.")
    else:
        retrasos['DIF'] = ((retrasos['SALIDA'] - retrasos['PROMESA']).dt.total_seconds() / 3600).round(1)
        print("\n⚠️ LISTADO DE RETRASOS CRÍTICOS:")
        print(retrasos[['Nº REMISION', 'PROMESA', 'SALIDA', 'DIF']].sort_values(by='DIF', ascending=False).to_string(index=False))

# 5. DIAGRAMA DE GANTT INTERACTIVO (CORREGIDO)
def graficar_gantt_interactivo(modo):
    if modo == "1":
        fecha = input("Fecha (AAAA-MM-DD): ").strip()
        df_f = res_fig[res_fig['INICIO_REAL'].dt.strftime('%Y-%m-%d') == fecha].copy()
        df_m = res_mall[res_mall['INICIO_REAL'].dt.strftime('%Y-%m-%d') == fecha].copy()
        titulo = f"Gantt Diario - {fecha}"
    else:
        try:
            sem = int(input("Semana: "))
            df_f = res_fig[res_fig['SEMANA'] == sem].copy()
            df_m = res_mall[res_mall['SEMANA'] == sem].copy()
            titulo = f"Gantt Semanal - Sem {sem}"
        except: return

    df_f['Maquina'], df_m['Maquina'] = 'FIGURADO', 'MALLAS'
    df_gantt = pd.concat([df_f, df_m])
    if df_gantt.empty: print("Sin datos."); return

    # Corrección de parámetros 'x_start' y 'x_end' para evitar el error de la imagen
    fig = px.timeline(df_gantt, x_start="INICIO_REAL", x_end="FIN_REAL", y="Maquina", color="Nº REMISION",
                      title=titulo, hover_data=["Nº REMISION", "FECHA_PROMESA"], template="plotly_white")
    fig.update_yaxes(autorange="reversed")
    fig.update_layout(showlegend=False, height=400)
    fig.show()

# 6. MENÚ DE USUARIO
def menu():
    while True:
        print(f"\n{'~'*50}\n Modulo solución \n EJERCICIO (A) WSPT\n{'~'*50}")
        print("1. Consolidado DIARIO")
        print("2. Consolidado SEMANAL")
        print("3. Tiempo de Flujo Promedio")
        print("4. Diagrama de Gantt Interactivo")
        print("5. Rastrear Remisión")
        print("6. Dashboard de Desempeño (KPIs)")
        print("7. Reporte de Retrasos Críticos")
        print("8. Salir")

        op = input("\nSeleccione: ")
        if op == "1":
            diario = stat_fig[['Fecha', 'Hechos', 'Pendientes']].merge(stat_mall[['Fecha', 'Hechos', 'Pendientes']], on='Fecha', suffixes=('_Fig', '_Mall'))
            print("\n--- REPORTE DIARIO DE PRODUCCIÓN ---\n", diario.to_string(index=False))
        elif op == "2":
            sf = stat_fig.groupby('Semana').agg({'Hechos': 'sum', 'Pendientes': 'last'})
            sm = stat_mall.groupby('Semana').agg({'Hechos': 'sum', 'Pendientes': 'last'})
            print("\n--- REPORTE SEMANAL DE PRODUCCIÓN ---\n", sf.merge(sm, on='Semana', suffixes=('_Fig', '_Mall')))
        elif op == "3":
            print(f"\n📊 FLUJO PROMEDIO: {calcular_tiempo_flujo()} HORAS HÁBILES")
        elif op == "4":
            sub = input("1. Diario / 2. Semanal: ")
            graficar_gantt_interactivo(sub)
        elif op == "5":
            n = input("Nº Remisión: ").strip()
            f, m = res_fig[res_fig['Nº REMISION'] == n], res_mall[res_mall['Nº REMISION'] == n]
            if f.empty and m.empty: print("No encontrada."); continue
            salida = max(f['FIN_REAL'].max() if not f.empty else pd.Timestamp.min, m['FIN_REAL'].max() if not m.empty else pd.Timestamp.min)
            print(f"Salida Estimada: {salida}")
        elif op == "6":
            calcular_indicadores()
        elif op == "7":
            reporte_retrasos()
        elif op == "8":
            break

if __name__ == "__main__":
    menu()

# "///////////////////////////////////////////////"
#
#  TALLER T1 - ITEM (b)  |  WSPT entre disponibles
#
# "///////////////////////////////////////////////"

!pip -q install pandas openpyxl ipywidgets plotly gdown

import pandas as pd
import numpy as np
import os
from datetime import datetime, timedelta, time
from IPython.display import display
from ipywidgets import IntText, Button, VBox, Output, Dropdown, HBox
from google.colab import files
import plotly.express as px
import plotly.io as pio
from google.colab import output

# ----------------------------
# Cargar datos
# ----------------------------
FILE_ID = "1eH_I3pJ7dZ-1pcwc-PJVjd3yYNkADg9N"
FILE_PATH = "/content/REMISIONES ENERO Y FEBRERO 2011.xlsx"
SHEET = "Simulacion_SPT"

# Descarga automática del archivo desde tu Drive
if not os.path.exists(FILE_PATH):
    print(" Descargando base de datos desde Google Drive...")
    !gdown --id {FILE_ID} -O "{FILE_PATH}" -q
else:
    print(" El archivo se encuentra en el entorno temporal.")

df_base = pd.read_excel(FILE_PATH, sheet_name=SHEET)
df_base.columns = [str(c).strip() for c in df_base.columns]

def find_col_contains(keyword_upper):
    for c in df_base.columns:
        if keyword_upper in c.upper():
            return c
    return None

REM_COL = find_col_contains("REMISION")

# r_j
candidatos_r = [c for c in df_base.columns if "R_J" in c.upper() and "LLEG" in c.upper()]
R_COL = candidatos_r[0] if len(candidatos_r)>0 else None
if R_COL is None:
    for name in ["r_j (llegada)", "r_j (llegada 00:00)"]:
        if name in df_base.columns:
            R_COL = name
            break

# w_j
W_COL = None
for name in ["w_j (# tipos)", "w_j (# tipos en remisión)"]:
    if name in df_base.columns:
        W_COL = name
        break
if W_COL is None:
    W_COL = find_col_contains("W_J")

# d_j (opcional para indicadores extra)
D_COL = None
for name in ["d_j promesa", "d_j (promesa)", "d_j (promesa: +2 días, 3pm; NO cuenta domingos)"]:
    if name in df_base.columns:
        D_COL = name
        break
if D_COL is None:
    D_COL = find_col_contains("D_J")

if REM_COL is None or R_COL is None or W_COL is None:
    print(" Columnas disponibles:")
    display(df_base.columns)
    raise ValueError("No existe REM_COL o R_COL o W_COL. Ajusta nombres.")

# kilos
for c in ["Figurado","Mallas","Materia Prima"]:
    if c not in df_base.columns:
        df_base[c] = 0.0
df_base[["Figurado","Mallas","Materia Prima"]] = df_base[["Figurado","Mallas","Materia Prima"]].fillna(0.0)

# normalizar fechas
df_base[R_COL] = pd.to_datetime(df_base[R_COL], errors="coerce").dt.normalize()  # 00:00
if D_COL is not None and D_COL in df_base.columns:
    df_base[D_COL] = pd.to_datetime(df_base[D_COL], errors="coerce")
else:
    D_COL = None

# w_j
df_base[W_COL] = pd.to_numeric(df_base[W_COL], errors="coerce").fillna(1).astype(int)

print("Archivo se descargó desde Drive.")
print("Hoja:", SHEET)
print("Filas:", len(df_base))
print("Remisiones únicas:", df_base[REM_COL].nunique())
print("Columnas usadas:", {"REM_COL":REM_COL, "R_COL":R_COL, "W_COL":W_COL, "D_COL":D_COL})

# ----------------------------
# Calendario operativo: domingo NO se trabaja
# ----------------------------
def is_sunday(dt: datetime) -> bool:
    return dt.weekday() == 6

def move_to_monday_0000(dt: datetime) -> datetime:
    if not is_sunday(dt):
        return dt
    return datetime.combine((dt + timedelta(days=1)).date(), time(0,0))

def add_work_hours_skip_sundays(start: datetime, hours: float) -> datetime:
    """Suma horas de trabajo (lunes-sábado 24h). Domingo no avanza."""
    if hours < 0:
        raise ValueError("hours debe ser >= 0")
    cur = move_to_monday_0000(start)
    remaining = float(hours)

    while remaining > 1e-12:
        cur = move_to_monday_0000(cur)

        cur_hour = cur.hour + cur.minute/60 + cur.second/3600 + cur.microsecond/3600e6
        avail = 24.0 - cur_hour
        if avail <= 1e-12:
            cur = datetime.combine((cur + timedelta(days=1)).date(), time(0,0))
            continue

        step = avail if remaining >= avail else remaining
        cur = cur + timedelta(hours=step)
        remaining -= step

        if cur.hour == 0 and cur.minute == 0 and cur.second == 0 and cur.microsecond == 0:
            cur = datetime.combine(cur.date(), time(0,0))

    return cur

# ----------------------------
# centro + p_horas + w_j
# ----------------------------
dfB = df_base.copy()
dfB["r_j"] = dfB[R_COL].dt.to_pydatetime()
dfB["w_j"] = dfB[W_COL].astype(int)

def centro(row):
    fig = float(row["Figurado"])
    mal = float(row["Mallas"])
    if fig > 0 and mal == 0:
        return "Figurado"
    if mal > 0 and fig == 0:
        return "Mallas"
    if fig == 0 and mal == 0:
        return "MP"
    return "Mixto"

dfB["centro"] = dfB.apply(centro, axis=1)

dfB["p_horas"] = 0.0
dfB.loc[dfB["centro"]=="Figurado","p_horas"] = dfB.loc[dfB["centro"]=="Figurado","Figurado"]/2600.0
dfB.loc[dfB["centro"]=="Mallas","p_horas"]   = dfB.loc[dfB["centro"]=="Mallas","Mallas"]/800.0
dfB.loc[dfB["centro"]=="Mixto","p_horas"]    = dfB.loc[dfB["centro"]=="Mixto","Figurado"]/2600.0 + dfB.loc[dfB["centro"]=="Mixto","Mallas"]/800.0

# ----------------------------
# Programación WSPT entre disponibles por centro
# ----------------------------
def programar_wspt_disponibles(df_jobs: pd.DataFrame, maquina: str) -> pd.DataFrame:
    if df_jobs.empty:
        return pd.DataFrame(columns=["maquina","remision","r_j","p_horas","w_j","ratio_p_w","start","C_j","flow_time_h"])

    tmp = df_jobs.sort_values("r_j").copy()
    pendientes = set(tmp.index)
    t = move_to_monday_0000(min(tmp["r_j"]))

    rows = []
    while pendientes:
        disponibles = [i for i in pendientes if tmp.at[i,"r_j"] <= t]

        if not disponibles:
            i_next = min(pendientes, key=lambda i: tmp.at[i,"r_j"])
            t = move_to_monday_0000(tmp.at[i_next,"r_j"])
            continue

        def key(i):
            pj = float(tmp.at[i,"p_horas"])
            w  = int(tmp.at[i,"w_j"]) if int(tmp.at[i,"w_j"]) > 0 else 1
            return (pj / w, pj, tmp.at[i,"r_j"], int(tmp.at[i,REM_COL]))

        i = min(disponibles, key=key)

        rj = tmp.at[i,"r_j"]
        pj = float(tmp.at[i,"p_horas"])
        w  = int(tmp.at[i,"w_j"]) if int(tmp.at[i,"w_j"]) > 0 else 1

        start = move_to_monday_0000(max(t, rj))
        end   = add_work_hours_skip_sundays(start, pj)

        flow_h = (end - rj).total_seconds()/3600.0

        rows.append({
            "maquina": maquina,
            "remision": int(tmp.at[i,REM_COL]),
            "r_j": rj,
            "p_horas": pj,
            "w_j": w,
            "ratio_p_w": pj / w,
            "start": start,
            "C_j": end,
            "flow_time_h": flow_h
        })

        t = end
        pendientes.remove(i)

    return pd.DataFrame(rows)

sched_fig = programar_wspt_disponibles(dfB[dfB["centro"]=="Figurado"], "Figurado")
sched_mal = programar_wspt_disponibles(dfB[dfB["centro"]=="Mallas"], "Mallas")
sched_mix = programar_wspt_disponibles(dfB[dfB["centro"]=="Mixto"], "Mixto")

# MP: p=0
df_mp = dfB[dfB["centro"]=="MP"].copy()
sched_mp = pd.DataFrame({
    "maquina":"MP",
    "remision": df_mp[REM_COL].astype(int),
    "r_j": df_mp["r_j"],
    "p_horas": 0.0,
    "w_j": df_mp["w_j"].astype(int),
    "ratio_p_w": 0.0
})
sched_mp["start"] = sched_mp["r_j"].apply(move_to_monday_0000)
sched_mp["C_j"] = sched_mp["start"]
sched_mp["flow_time_h"] = (pd.to_datetime(sched_mp["C_j"]) - pd.to_datetime(sched_mp["r_j"])).dt.total_seconds()/3600.0

sched_b = pd.concat([sched_fig, sched_mal, sched_mix, sched_mp], ignore_index=True)

# ----------------------------
# Objetivo principal: Σ w_j C_j
#
# ----------------------------
t0 = move_to_monday_0000(min(dfB["r_j"]))
sched_b["C_j"] = pd.to_datetime(sched_b["C_j"])
sched_b["C_h_desde_t0"] = (sched_b["C_j"] - pd.to_datetime(t0)).dt.total_seconds()/3600.0

sum_wC = float((sched_b["w_j"] * sched_b["C_h_desde_t0"]).sum())
avg_flow_h = float(sched_b["flow_time_h"].mean())

# Indicadores extra vs promesa (si existe)
if D_COL is not None:
    dj_map = df_base[[REM_COL, D_COL]].rename(columns={REM_COL:"remision"})
    sched_b = sched_b.merge(dj_map, on="remision", how="left")
    sched_b[D_COL] = pd.to_datetime(sched_b[D_COL], errors="coerce")
    sched_b["L_j_h"] = (sched_b["C_j"] - sched_b[D_COL]).dt.total_seconds()/3600.0
    sched_b["T_j_h"] = sched_b["L_j_h"].clip(lower=0)
    sched_b["E_j_h"] = (-sched_b["L_j_h"]).clip(lower=0)
    sched_b["U_j"] = (sched_b["L_j_h"] > 0).astype(int)

    num_tardios = int(sched_b["U_j"].sum())
    pct_tardios = float(sched_b["U_j"].mean()*100)
    tardanza_prom = float(sched_b["T_j_h"].mean())
else:
    num_tardios = None
    pct_tardios = None
    tardanza_prom = None

resumen_b = pd.DataFrame({
    "Métrica": [
        "# remisiones",
        "Σ w_j C_j (horas desde t0)",
        "t0 (origen)",
        "Flow promedio (h)",
        "# tardíos (ΣU_j)" if num_tardios is not None else "—",
        "% tardíos" if pct_tardios is not None else "—",
        "Tardanza promedio T_j (h)" if tardanza_prom is not None else "—",
    ],
    "Valor": [
        int(sched_b["remision"].nunique()),
        round(sum_wC, 4),
        str(t0),
        round(avg_flow_h, 4),
        num_tardios if num_tardios is not None else "NA",
        round(pct_tardios, 2) if pct_tardios is not None else "NA",
        round(tardanza_prom, 4) if tardanza_prom is not None else "NA",
    ]
})

print("\n RESUMEN:")
display(resumen_b)

# ----------------------------
# Resumen diario y semanal
# ----------------------------
def partir_intervalo_por_dia(start: datetime, end: datetime):
    out = []
    cur = start
    while cur < end:
        if cur.weekday() == 6:
            cur = datetime.combine((cur + timedelta(days=1)).date(), time(0,0))
            continue
        next_midnight = datetime.combine((cur + timedelta(days=1)).date(), time(0,0))
        seg_end = min(end, next_midnight)
        hrs = (seg_end - cur).total_seconds()/3600.0
        if hrs > 0:
            out.append((cur.date(), hrs))
        cur = seg_end
    return out

rows = []
for _, r in sched_b.iterrows():
    st = pd.to_datetime(r["start"]).to_pydatetime()
    en = pd.to_datetime(r["C_j"]).to_pydatetime()
    for fecha, hrs in partir_intervalo_por_dia(st, en):
        rows.append({"fecha": pd.to_datetime(fecha),
                     "maquina": r["maquina"],
                     "remision": int(r["remision"]),
                     "horas_trabajadas": hrs})

df_dia_b = pd.DataFrame(rows)

resumen_diario_b = (df_dia_b.groupby(["fecha","maquina"])
                  .agg(horas=("horas_trabajadas","sum"),
                       remisiones=("remision","nunique"))
                  .reset_index()
                  .sort_values(["fecha","maquina"]))

resumen_diario_b["año"] = resumen_diario_b["fecha"].dt.isocalendar().year.astype(int)
resumen_diario_b["semana"] = resumen_diario_b["fecha"].dt.isocalendar().week.astype(int)

resumen_semanal_b = (resumen_diario_b.groupby(["año","semana","maquina"])
                   .agg(horas=("horas","sum"),
                        remisiones=("remisiones","sum"))
                   .reset_index()
                   .sort_values(["año","semana","maquina"]))

print("\n Resumen diario  — primeras filas:")
display(resumen_diario_b.head(10))
print("\n Resumen semanal  — primeras filas:")
display(resumen_semanal_b.head(10))


# ----------------------------
# Diagrama de Gantt (Plotly + ipywidgets)
# ----------------------------
print("\n" + "~"*50)
print(" DIAGRAMA DE GANTT \n PARA WSPT ELEGIBLE X SEMANA")
print("~"*50)

pio.renderers.default = 'colab'
output.enable_custom_widget_manager()

sched_b_gantt = sched_b.copy()
sched_b_gantt["fecha_inicio"] = pd.to_datetime(sched_b_gantt["start"]).dt.date
sched_b_gantt["semana_iso"] = pd.to_datetime(sched_b_gantt["start"]).dt.isocalendar().week
sched_b_gantt["remision_str"] = sched_b_gantt["remision"].astype(str)

gantt_view = Dropdown(options=['Todo', 'Por Semana', 'Por Día'], value='Todo', description='Vista:')
gantt_filter = Dropdown(options=['-'], value='-', description='Filtro:')
gantt_out = Output()

def update_gantt_filters(*args):
    if gantt_view.value == 'Todo':
        gantt_filter.options = ['-']
        gantt_filter.value = '-'
        gantt_filter.disabled = True
    elif gantt_view.value == 'Por Semana':
        semanas = sorted(sched_b_gantt["semana_iso"].unique())
        gantt_filter.options = [f"Semana {s}" for s in semanas]
        if len(gantt_filter.options) > 0: gantt_filter.value = gantt_filter.options[0]
        gantt_filter.disabled = False
    elif gantt_view.value == 'Por Día':
        dias = sorted(sched_b_gantt["fecha_inicio"].unique())
        gantt_filter.options = [str(d) for d in dias]
        if len(gantt_filter.options) > 0: gantt_filter.value = gantt_filter.options[0]
        gantt_filter.disabled = False
    render_gantt()

def render_gantt(*args):
    gantt_out.clear_output(wait=True)
    with gantt_out:
        if gantt_view.value == 'Todo':
            df_plot = sched_b_gantt.copy()
            title = "Diagrama de Gantt - Toda la Programación WSPT"
        elif gantt_view.value == 'Por Semana':
            s = int(str(gantt_filter.value).replace("Semana ", ""))
            df_plot = sched_b_gantt[sched_b_gantt["semana_iso"] == s].copy()
            title = f"Diagrama de Gantt - Semana {s}"
        else:
            d = pd.to_datetime(gantt_filter.value).date()
            df_plot = sched_b_gantt[sched_b_gantt["fecha_inicio"] == d].copy()
            title = f"Diagrama de Gantt - Día {d}"

        df_plot = df_plot[df_plot["p_horas"] > 0].copy()

        if df_plot.empty:
            print("No hay trabajos de procesamiento en este periodo (solo Materia Prima).")
            return

        fig = px.timeline(
            df_plot, x_start="start", x_end="C_j", y="maquina", color="remision_str",
            hover_name="remision",
            hover_data={"w_j": True, "p_horas": ":.3f", "start": "|%Y-%m-%d %H:%M", "C_j": "|%Y-%m-%d %H:%M", "remision_str": False},
            title=title,
            labels={"maquina": "Centro de Trabajo", "start": "Inicio", "C_j": "Fin", "w_j": "Peso", "remision_str": "Remisión"}
        )
        fig.update_yaxes(autorange="reversed")
        fig.update_layout(height=450, xaxis_title="Línea de Tiempo", font=dict(size=11), showlegend=False)
        display(fig)

gantt_view.observe(update_gantt_filters, 'value')
gantt_filter.observe(render_gantt, 'value')

display(HBox([gantt_view, gantt_filter]))
display(gantt_out)
update_gantt_filters()


# ----------------------------
# Buscador por remisión
# ----------------------------
def mostrar_remision_b(rem_id: int):
    rem_id = int(rem_id)

    base = dfB[dfB[REM_COL].astype(int) == rem_id]
    if base.empty:
        print(f" Remisión {rem_id} no existe")
        return
    base = base.iloc[0]

    sch = sched_b[sched_b["remision"].astype(int) == rem_id]
    sch = sch.iloc[0] if not sch.empty else None

    print("~"*40)
    print(f" REMISIÓN {rem_id} ")
    print("~"*40)
    print(f"Centro: {base['centro']}")
    print(f"r_j:    {base['r_j']}")
    if D_COL is not None and pd.notna(base.get(D_COL, pd.NaT)):
        print(f"d_j:    {base[D_COL]}")
    print(f"w_j:    {int(base['w_j'])}")

    print("\nKilos:")
    print(f" - Figurado:      {float(base['Figurado']):,.2f} kg")
    print(f" - Mallas:        {float(base['Mallas']):,.2f} kg")
    print(f" - Materia Prima: {float(base['Materia Prima']):,.2f} kg")

    print("\nTiempo proceso y prioridad:")
    print(f" p_horas = {float(base['p_horas']):.6f} h")
    print(f" p/w =    {float(base['p_horas'])/max(int(base['w_j']),1):.6f}")

    if sch is not None:
        print("\n--- Programación ---")
        print(f"Máquina: {sch['maquina']}")
        print(f"Start:   {sch['start']}")
        print(f"C_j:     {sch['C_j']}")
        print(f"C_h t0:  {float(sch['C_h_desde_t0']):.4f}")
        print(f"Flow(h): {float(sch['flow_time_h']):.4f}")
        if D_COL is not None and "T_j_h" in sched_b.columns:
            print(f"T_j(h):  {float(sch['T_j_h']):.4f}")
            print(f"U_j:     {int(sch['U_j'])}")
    print("~"*50 + "\n")

inp = IntText(value=int(dfB[REM_COL].iloc[0]), description="Remisión:")
btn = Button(description="Buscar")
out = Output()

def _click(_):
    with out:
        out.clear_output()
        mostrar_remision_b(inp.value)

btn.on_click(_click)
display(VBox([inp, btn, out]))

# ============================================================
#  Item C
# Common Due Date diario 3:00 pm
#  Objetivo: minimizar Σ (E_j + T_j)
#
# ============================================================

!pip -q install pandas openpyxl ipywidgets plotly gdown

import pandas as pd
import numpy as np
import os
from datetime import datetime, timedelta, time
from IPython.display import display
from ipywidgets import IntText, Button, VBox, Output, Dropdown, HBox
from google.colab import files
import plotly.express as px
import plotly.io as pio
from google.colab import output

# ----------------------------
# Cargar datos
# ----------------------------
FILE_ID = "1eH_I3pJ7dZ-1pcwc-PJVjd3yYNkADg9N"
FILE_PATH = "/content/REMISIONES ENERO Y FEBRERO 2011.xlsx"
SHEET = "Simulacion_SPT"

# Si el archivo no existe en el entorno, se descarga de Drive automáticamente
if not os.path.exists(FILE_PATH):
    print(" Descargando base de datos desde Google Drive...")
    !gdown --id {FILE_ID} -O "{FILE_PATH}" -q
else:
    print(" El archivo se puso en el entorno temporal.")

df = pd.read_excel(FILE_PATH, sheet_name=SHEET)
df.columns = [str(c).strip() for c in df.columns]

# Nombres típicos en tu hoja
REM_COL = "Nº REMISION"
R_COL   = "r_j (llegada)"
W_COL   = "w_j (# tipos)"
D_COL   = "d_j promesa"

for c in ["Figurado","Mallas","Materia Prima"]:
    if c not in df.columns:
        df[c] = 0.0
df[["Figurado","Mallas","Materia Prima"]] = df[["Figurado","Mallas","Materia Prima"]].fillna(0.0)

df[R_COL] = pd.to_datetime(df[R_COL], errors="coerce").dt.normalize()  # 00:00
if W_COL in df.columns:
    df[W_COL] = pd.to_numeric(df[W_COL], errors="coerce").fillna(1).astype(int)
if D_COL in df.columns:
    df[D_COL] = pd.to_datetime(df[D_COL], errors="coerce")

print(" Datos cargados:", len(df), "filas | remisiones únicas:", df[REM_COL].nunique())

# ----------------------------
# Calendario operativo: domingo NO se trabaja
# ----------------------------
def is_sunday(dt: datetime) -> bool:
    return dt.weekday() == 6

def move_to_monday_0000(dt: datetime) -> datetime:
    if not is_sunday(dt):
        return dt
    return datetime.combine((dt + timedelta(days=1)).date(), time(0,0))

def add_work_hours_skip_sundays(start: datetime, hours: float) -> datetime:
    """Suma horas de trabajo (lun-sáb 24h). Domingo no avanza."""
    if hours < 0:
        raise ValueError("hours debe ser >= 0")
    cur = move_to_monday_0000(start)
    remaining = float(hours)

    while remaining > 1e-12:
        cur = move_to_monday_0000(cur)
        cur_hour = cur.hour + cur.minute/60 + cur.second/3600 + cur.microsecond/3600e6
        avail = 24.0 - cur_hour

        if avail <= 1e-12:
            cur = datetime.combine((cur + timedelta(days=1)).date(), time(0,0))
            continue

        step = avail if remaining >= avail else remaining
        cur = cur + timedelta(hours=step)
        remaining -= step

        if cur.hour == 0 and cur.minute == 0 and cur.second == 0 and cur.microsecond == 0:
            cur = datetime.combine(cur.date(), time(0,0))

    return cur

# ----------------------------
#
# ----------------------------
dfC = df.copy()

# día operativo: si r_j cae domingo -> lunes
dfC["dia_operativo"] = dfC[R_COL].apply(lambda x: (x + pd.Timedelta(days=1)) if x.weekday()==6 else x)

# centro por remisión
def centro(row):
    fig = float(row["Figurado"])
    mal = float(row["Mallas"])
    if fig > 0 and mal == 0:
        return "Figurado"
    if mal > 0 and fig == 0:
        return "Mallas"
    if fig == 0 and mal == 0:
        return "MP"
    return "Mixto"

dfC["centro"] = dfC.apply(centro, axis=1)

# tiempos de proceso (horas) por centro
dfC["p_horas"] = 0.0
dfC.loc[dfC["centro"]=="Figurado","p_horas"] = dfC.loc[dfC["centro"]=="Figurado","Figurado"]/2600.0
dfC.loc[dfC["centro"]=="Mallas","p_horas"]   = dfC.loc[dfC["centro"]=="Mallas","Mallas"]/800.0
dfC.loc[dfC["centro"]=="Mixto","p_horas"]    = dfC.loc[dfC["centro"]=="Mixto","Figurado"]/2600.0 + dfC.loc[dfC["centro"]=="Mixto","Mallas"]/800.0

# d común diario de: 15:00 del día operativo
def due_date_3pm(dia):
    return datetime.combine(pd.to_datetime(dia).date(), time(15,0))

# ----------------------------
# 3) Algoritmo Common Due Date
#    - Si d <= Cmax: sets A y B (B FIFO, A LIFO)
#    - Si d > Cmax: LPT y retrasar inicio hasta que el último termine en d
# ----------------------------
def secuencia_cdd_min_abs(jobs):
    """
    jobs: lista de dicts con {"remision":id, "p":horas}
    devuelve: (secuencia_ids, start_offset_h)
    """
    # ordenar SPT
    jobs_sorted = sorted(jobs, key=lambda x: (x["p"], x["remision"]))
    n = len(jobs_sorted)
    if n == 0:
        return [], 0.0

    d = 15.0  # horas desde 00:00
    Cmax = sum(j["p"] for j in jobs_sorted)

    # Caso d > Cmax: todo sería "early", conviene LPT y retrasar inicio
    if d > Cmax + 1e-12:
        seq = [j["remision"] for j in sorted(jobs_sorted, key=lambda x: (-x["p"], x["remision"]))]
        start_offset = d - Cmax  # retraso para terminar cerca de 15:00
        return seq, start_offset


    R = Cmax - d
    L = d
    A = []
    B = []

    # i = n..1 (empezar por el más grande dentro de SPT)
    for j in reversed(jobs_sorted):
        if R >= L:
            A.append(j)
            R -= j["p"]
        else:
            B.append(j)
            L -= j["p"]

    seq_B = [j["remision"] for j in B]
    seq_A = [j["remision"] for j in reversed(A)]
    seq = seq_B + seq_A
    return seq, 0.0

def simular_dia_centro(df_sub, dia_operativo, centro_nombre):
    """
    Simula un día y un centro, usando secuencia CDD.
    Retorna dataframe con start/C/E/T/U por remisión.
    """
    # due date del día
    d_dt = due_date_3pm(dia_operativo)


    if centro_nombre == "MP":
        out = df_sub.copy()
        out["maquina"] = "MP"
        out["start"] = d_dt
        out["C_j"] = d_dt
        out["E_j_h"] = 0.0
        out["T_j_h"] = 0.0
        out["U_j"] = 0
        out["d_comun"] = d_dt
        out["pos"] = 1
        return out[[REM_COL, "maquina", "dia_operativo", "pos", "p_horas", "start", "C_j", "d_comun", "E_j_h", "T_j_h", "U_j"]]

    # armar lista jobs
    jobs = [{"remision": int(r[REM_COL]), "p": float(r["p_horas"])} for _, r in df_sub.iterrows()]

    seq_ids, offset_h = secuencia_cdd_min_abs(jobs)

    # inicio del día (00:00) con posible offset si d > Cmax
    start_day = datetime.combine(pd.to_datetime(dia_operativo).date(), time(0,0))
    start_day = move_to_monday_0000(start_day)
    reloj = start_day + timedelta(hours=float(offset_h))

    # mapa rápido p
    p_map = {j["remision"]: j["p"] for j in jobs}

    rows = []
    for k, rid in enumerate(seq_ids, start=1):
        pj = p_map[rid]
        st = reloj
        en = add_work_hours_skip_sundays(st, pj)

        E = max((d_dt - en).total_seconds()/3600.0, 0.0)
        T = max((en - d_dt).total_seconds()/3600.0, 0.0)
        U = 1 if T > 1e-12 else 0

        rows.append({
            REM_COL: rid,
            "maquina": centro_nombre,
            "dia_operativo": pd.to_datetime(dia_operativo), # Removed .date() to ensure Timestamp consistency
            "pos": k,
            "p_horas": pj,
            "start": st,
            "C_j": en,
            "d_comun": d_dt,
            "E_j_h": E,
            "T_j_h": T,
            "U_j": U
        })
        reloj = en

    return pd.DataFrame(rows)

# ----------------------------
# Ejecutar programación por día y por centro
# ----------------------------
salidas = []

for dia, df_dia in dfC.groupby("dia_operativo"):
    for centro_nombre in ["Figurado", "Mallas", "MP", "Mixto"]:
        df_sub = df_dia[df_dia["centro"] == centro_nombre].copy()
        if df_sub.empty:
            continue
        salidas.append(simular_dia_centro(df_sub, dia, centro_nombre))

sched_c = pd.concat(salidas, ignore_index=True)

# ----------------------------
# Indicadores
# ----------------------------
sched_c["E_plus_T"] = sched_c["E_j_h"] + sched_c["T_j_h"]

total_ET = float(sched_c["E_plus_T"].sum())
avg_ET   = float(sched_c["E_plus_T"].mean())
total_E  = float(sched_c["E_j_h"].sum())
total_T  = float(sched_c["T_j_h"].sum())
num_tard = int(sched_c["U_j"].sum())
pct_tard = float(sched_c["U_j"].mean()*100)

resumen_c = pd.DataFrame({
    "Métrica": [
        "# remisiones",
        "Total Σ(E+T) [horas]",
        "Promedio (E+T) por remisión [h]",
        "Total Earliness ΣE [h]",
        "Total Tardiness ΣT [h]",
        "# tardíos (ΣU)",
        "% tardíos",
    ],
    "Valor": [
        int(sched_c[REM_COL].nunique()),
        round(total_ET, 4),
        round(avg_ET, 4),
        round(total_E, 4),
        round(total_T, 4),
        num_tard,
        round(pct_tard, 2),
    ]
})

print("\n RESUMEN:")
display(resumen_c)

# Resumen por día y centro
resumen_diario_c = (sched_c.groupby(["dia_operativo","maquina"])
                    .agg(
                        remisiones=(REM_COL,"nunique"),
                        total_E=("E_j_h","sum"),
                        total_T=("T_j_h","sum"),
                        total_ET=("E_plus_T","sum"),
                        tardios=("U_j","sum")
                    )
                    .reset_index()
                    .sort_values(["dia_operativo","maquina"]))

resumen_diario_c["% tardios"] = (resumen_diario_c["tardios"]/resumen_diario_c["remisiones"]*100).round(2)

print("\n Resumen DIARIO — primeras filas:")
display(resumen_diario_c.head(12))


tmp = resumen_diario_c.copy()
tmp["dia_operativo"] = pd.to_datetime(tmp["dia_operativo"])
tmp["anio"] = tmp["dia_operativo"].dt.isocalendar().year.astype(int)
tmp["semana"] = tmp["dia_operativo"].dt.isocalendar().week.astype(int)

resumen_semanal_c = (tmp.groupby(["anio","semana","maquina"])
                     .agg(
                         remisiones=("remisiones","sum"),
                         total_ET=("total_ET","sum"),
                         total_E=("total_E","sum"),
                         total_T=("total_T","sum"),
                         tardios=("tardios","sum")
                     )
                     .reset_index()
                     .sort_values(["anio","semana","maquina"]))


# ----------------------------
#
# ----------------------------
print("\n" + "~"*40)
print(" DIAGRAMA DE GANTT COMMON DUE DATE")
print("~"*40)

pio.renderers.default = 'colab'
output.enable_custom_widget_manager()

sched_c_gantt = sched_c.copy()


sched_c_gantt["fecha_inicio_str"] = pd.to_datetime(sched_c_gantt["start"]).dt.strftime('%Y-%m-%d')
sched_c_gantt["semana_iso"] = pd.to_datetime(sched_c_gantt["start"]).dt.isocalendar().week
sched_c_gantt["remision_str"] = sched_c_gantt[REM_COL].astype(str)

gantt_view = Dropdown(options=['Todo', 'Por Semana', 'Por Día'], value='Todo', description='Vista:')
gantt_filter = Dropdown(options=['-'], value='-', description='Filtro:')
gantt_out = Output()

def update_gantt_filters(*args):
    if gantt_view.value == 'Todo':
        gantt_filter.options = ['-']
        gantt_filter.value = '-'
        gantt_filter.disabled = True
    elif gantt_view.value == 'Por Semana':
        semanas = sorted(sched_c_gantt["semana_iso"].unique())
        gantt_filter.options = [f"Semana {s}" for s in semanas]
        if len(gantt_filter.options) > 0: gantt_filter.value = gantt_filter.options[0]
        gantt_filter.disabled = False
    elif gantt_view.value == 'Por Día':

        dias_str = sorted(sched_c_gantt["fecha_inicio_str"].unique())
        gantt_filter.options = dias_str
        if len(gantt_filter.options) > 0: gantt_filter.value = gantt_filter.options[0]
        gantt_filter.disabled = False
    render_gantt()

def render_gantt(*args):
    gantt_out.clear_output(wait=True)
    with gantt_out:
        if gantt_view.value == 'Todo':
            df_plot = sched_c_gantt.copy()
            title = "Diagrama de Gantt - Toda la Programación CDD"
        elif gantt_view.value == 'Por Semana':
            s = int(str(gantt_filter.value).replace("Semana ", ""))
            df_plot = sched_c_gantt[sched_c_gantt["semana_iso"] == s].copy()
            title = f"Diagrama de Gantt - Semana {s} (CDD)"
        else:

            d_str = str(gantt_filter.value)
            df_plot = sched_c_gantt[sched_c_gantt["fecha_inicio_str"] == d_str].copy()
            title = f"Diagrama de Gantt - Día {d_str} (CDD)"

        # Ocultar la materia prima que dura 0 horas
        df_plot = df_plot[df_plot["p_horas"] > 0].copy()

        if df_plot.empty:
            print("No hay trabajos de procesamiento en este periodo (solo Materia Prima).")
            return

        fig = px.timeline(
            df_plot, x_start="start", x_end="C_j", y="maquina", color="remision_str",
            hover_name=REM_COL,
            hover_data={"p_horas": ":.3f", "start": "|%Y-%m-%d %H:%M", "C_j": "|%Y-%m-%d %H:%M", "remision_str": False},
            title=title,
            labels={"maquina": "Centro de Trabajo", "start": "Inicio", "C_j": "Fin", "remision_str": "Remisión"}
        )
        fig.update_yaxes(autorange="reversed")
        fig.update_layout(height=450, xaxis_title="Línea de Tiempo", font=dict(size=11), showlegend=False)
        display(fig)

gantt_view.observe(update_gantt_filters, 'value')
gantt_filter.observe(render_gantt, 'value')

display(HBox([gantt_view, gantt_filter]))
display(gantt_out)
update_gantt_filters()


# ----------------------------

# ----------------------------
def mostrar_remision_c(rem_id: int):
    rem_id = int(rem_id)
    base = dfC[dfC[REM_COL].astype(int) == rem_id]
    if base.empty:
        print(f" Esa Remisión {rem_id} no existe en el archivo")
        return
    base = base.iloc[0]

    sch = sched_c[sched_c[REM_COL].astype(int) == rem_id]
    if sch.empty:
        print("No se encuentra en la salida sched.")
        return
    sch = sch.iloc[0]

    print("====================================")
    print(f"REMISIÓN {rem_id} ")
    print("====================================")
    print(f"Día operativo: {sch['dia_operativo']}")
    print(f"Centro:        {sch['maquina']}")
    print(f"p_horas:       {float(sch['p_horas']):.6f}")
    print(f"Due común d:   {sch['d_comun']}")
    print(f"Start:         {sch['start']}")
    print(f"C_j:           {sch['C_j']}")
    print(f"E_j (h):       {float(sch['E_j_h']):.4f}")
    print(f"T_j (h):       {float(sch['T_j_h']):.4f}")
    print(f"U_j:           {int(sch['U_j'])}")
    print("-------------------------------------")
    print("Kilos:")
    print(f"  Figurado: {float(base['Figurado']):,.2f} | Mallas: {float(base['Mallas']):,.2f} | MP: {float(base['Materia Prima']):,.2f}")
    if W_COL in dfC.columns:
        print(f"w_j (# tipos): {int(base[W_COL])}")
    if D_COL in dfC.columns:
        print(f"d_j promesa (otra regla): {base[D_COL]}")
    print("====================================\n")

inp = IntText(value=int(dfC[REM_COL].iloc[0]), description="Remisión:")
btn = Button(description="Buscar")
out = Output()

def _click(_):
    with out:
        out.clear_output()
        mostrar_remision_c(inp.value)

btn.on_click(_click)
display(VBox([inp, btn, out]))

# ----------------------------

#///////////////////////////////////////////////
# Punto D Taller
#///////////////////////////////////////////////

import pandas as pd
import numpy as np
import plotly.express as px
from datetime import datetime
import io
import requests  # Nueva librería necesaria

# ==========================================
# 1. CARGA DE DATOS DESDE GITHUB
# ==========================================
# URL directa del archivo en GitHub
url_github = "https://github.com/Fev23/Datos-entrada-Taller-Plan-Eduyn/raw/refs/heads/main/datos%20entrada%20A%20dias.xlsx"

try:
    print("Conectando con GitHub para extraer datos...")
    response = requests.get(url_github)
    response.raise_for_status() # Verifica que la descarga fue exitosa

    # Leer el contenido binario del archivo usando io.BytesIO
    df = pd.read_excel(io.BytesIO(response.content))
    print("Datos cargados exitosamente.\n")
except Exception as e:
    print(f"Error al intentar descargar o leer el archivo desde GitHub: {e}")
    exit()

# Limpieza inicial
df.columns = [c.strip() for c in df.columns]
df['FECHA'] = pd.to_datetime(df['FECHA'])
df['Nº REMISION'] = df['Nº REMISION'].astype(str).str.strip()

# W_j: Importancia segun cantidad de tipos de producto
df['W_j'] = df['Cant tipos'].fillna(1).replace(0, 1)

# ==========================================
# 2. FECHAS DE ENTREGA d_j
# ==========================================
def calcular_promesa(rj):
    # Promesa: 2 dias despues a las 15:00. Domingos no cuentan.
    p = rj + pd.Timedelta(days=2)
    if p.weekday() == 6:
        p += pd.Timedelta(days=1)
    return p.replace(hour=15, minute=0, second=0)

df['FECHA_PROMESA'] = df['FECHA'].apply(calcular_promesa)
# Identificar la semana del ano
df['SEMANA_ISO'] = df['FECHA'].dt.isocalendar().week

# [EL RESTO DE TUS FUNCIONES SE MANTIENEN IGUAL]
# ==========================================
# 3. MOTORES DE SECUENCIACION ESTATICA (FUNCIONES)
# ==========================================

def agregar_horas_habiles(fecha_inicio, horas):
    actual = fecha_inicio
    restante = horas
    while restante > 0:
        if actual.weekday() == 6: # Es domingo, saltar
            actual += pd.Timedelta(days=1)
            actual = actual.replace(hour=0, minute=0, second=0)

        dias_para_domingo = 6 - actual.weekday()
        proximo_domingo = (actual + pd.Timedelta(days=dias_para_domingo)).replace(hour=0, minute=0, second=0)
        horas_al_domingo = (proximo_domingo - actual).total_seconds() / 3600.0

        if restante <= horas_al_domingo:
            actual += pd.Timedelta(hours=restante)
            restante = 0
        else:
            actual = proximo_domingo + pd.Timedelta(days=1)
            restante -= horas_al_domingo
    return actual

def aplicar_regla_ordenamiento(df_m, col_pj, regla):
    if regla == 'FCFS': df_m = df_m.sort_values(by='FECHA')
    elif regla == 'SPT': df_m = df_m.sort_values(by=col_pj)
    elif regla == 'WSPT':
        df_m['PRIO'] = df_m[col_pj] / df_m['W_j']
        df_m = df_m.sort_values(by='PRIO')
    elif regla == 'LPT': df_m = df_m.sort_values(by=col_pj, ascending=False)
    elif regla == 'EDD': df_m = df_m.sort_values(by='d_j_horas')
    elif regla == 'MST':
        df_m['PRIO'] = df_m['d_j_horas'] - df_m[col_pj]
        df_m = df_m.sort_values(by='PRIO')
    elif regla == 'CR':
        df_m['PRIO'] = df_m['d_j_horas'] / df_m[col_pj]
        df_m = df_m.sort_values(by='PRIO')
    elif regla == 'WLPT':
        df_m['PRIO'] = df_m[col_pj] * df_m['W_j']
        df_m = df_m.sort_values(by='PRIO', ascending=False)
    return df_m

def procesar_semana_estatica(df_semana, col_pj, regla):
    df_m = df_semana[df_semana[col_pj] > 0].copy()
    if df_m.empty: return []

    inicio_semana = df_m['FECHA'].min() - pd.Timedelta(days=df_m['FECHA'].min().weekday())
    inicio_semana = inicio_semana.replace(hour=0, minute=0, second=0)
    df_m['d_j_horas'] = (df_m['FECHA_PROMESA'] - inicio_semana).dt.total_seconds() / 3600.0

    df_m = aplicar_regla_ordenamiento(df_m, col_pj, regla)

    finalizados = []
    reloj = inicio_semana

    for _, row in df_m.iterrows():
        if reloj < row['FECHA']: reloj = row['FECHA'].replace(hour=0, minute=0, second=0)
        if reloj.weekday() == 6:
            reloj += pd.Timedelta(days=1)
            reloj = reloj.replace(hour=0, minute=0, second=0)

        inicio_tarea = reloj
        reloj = agregar_horas_habiles(reloj, row[col_pj])

        row_copy = row.copy()
        row_copy['INICIO_REAL'] = inicio_tarea
        row_copy['FIN_REAL'] = reloj
        row_copy['C_j_horas'] = (reloj - row_copy['FECHA']).total_seconds() / 3600.0
        finalizados.append(row_copy)
    return finalizados

def procesar_dia_estatico(df_dia, col_pj, regla, reloj_global):
    df_m = df_dia[df_dia[col_pj] > 0].copy()
    if df_m.empty: return [], reloj_global

    inicio_dia = df_m['FECHA'].min().replace(hour=0, minute=0, second=0)
    df_m['d_j_horas'] = (df_m['FECHA_PROMESA'] - inicio_dia).dt.total_seconds() / 3600.0

    df_m = aplicar_regla_ordenamiento(df_m, col_pj, regla)

    finalizados = []
    reloj = max(reloj_global, inicio_dia)

    for _, row in df_m.iterrows():
        if reloj < row['FECHA']: reloj = row['FECHA'].replace(hour=0, minute=0, second=0)
        if reloj.weekday() == 6:
            reloj += pd.Timedelta(days=1)
            reloj = reloj.replace(hour=0, minute=0, second=0)

        inicio_tarea = reloj
        reloj = agregar_horas_habiles(reloj, row[col_pj])

        row_copy = row.copy()
        row_copy['INICIO_REAL'] = inicio_tarea
        row_copy['FIN_REAL'] = reloj
        row_copy['C_j_horas'] = (reloj - row_copy['FECHA']).total_seconds() / 3600.0
        finalizados.append(row_copy)

    return finalizados, reloj

# ==========================================
# 4. EVALUACION GLOBAL Y RESTO DEL MENU
# ==========================================
def calcular_objetivos(df_resultados):
    if df_resultados.empty: return 0, 0, 0
    df_resultados['T_j'] = np.maximum(0, (df_resultados['FIN_REAL'] - df_resultados['FECHA_PROMESA']).dt.total_seconds() / 3600.0)
    df_resultados['U_j'] = (df_resultados['T_j'] > 0).astype(int)

    sum_Wj_Cj = np.sum(df_resultados['W_j'] * df_resultados['C_j_horas'])
    sum_Wj_Tj = np.sum(df_resultados['W_j'] * df_resultados['T_j'])
    sum_Uj = np.sum(df_resultados['U_j'])
    return sum_Wj_Cj, sum_Wj_Tj, sum_Uj

def evaluar_regla_semanal(regla):
    res_fig, res_mall = [], []
    for sem in df['SEMANA_ISO'].unique():
        df_sem = df[df['SEMANA_ISO'] == sem]
        res_fig.extend(procesar_semana_estatica(df_sem, 'pj fig', regla))
        res_mall.extend(procesar_semana_estatica(df_sem, 'pj mall', regla))
    return pd.DataFrame(res_fig), pd.DataFrame(res_mall)

def evaluar_regla_diaria(regla):
    res_fig, res_mall = [], []
    reloj_fig = pd.Timestamp.min
    reloj_mall = pd.Timestamp.min
    dias = df['FECHA'].dt.date.unique()
    dias.sort()
    for dia in dias:
        df_dia = df[df['FECHA'].dt.date == dia]
        fig_terminados, reloj_fig = procesar_dia_estatico(df_dia, 'pj fig', regla, reloj_fig)
        mall_terminados, reloj_mall = procesar_dia_estatico(df_dia, 'pj mall', regla, reloj_mall)
        res_fig.extend(fig_terminados)
        res_mall.extend(mall_terminados)
    return pd.DataFrame(res_fig), pd.DataFrame(res_mall)

res_fig_actual, res_mall_actual = pd.DataFrame(), pd.DataFrame()
regla_actual = "WSPT"

def graficar_gantt_interactivo(modo):
    if res_fig_actual.empty and res_mall_actual.empty:
        print("Debe ejecutar una regla primero.")
        return
    if modo == "1":
        fecha = input("Ingrese fecha (AAAA-MM-DD): ").strip()
        df_f = res_fig_actual[res_fig_actual['INICIO_REAL'].dt.strftime('%Y-%m-%d') == fecha].copy()
        df_m = res_mall_actual[res_mall_actual['INICIO_REAL'].dt.strftime('%Y-%m-%d') == fecha].copy()
        titulo = f"Gantt Diario Estatico ({regla_actual}) - {fecha}"
    else:
        try:
            sem = int(input("Ingrese numero de semana (ej. 1, 2, 3...): "))
            df_f = res_fig_actual[res_fig_actual['SEMANA_ISO'] == sem].copy()
            df_m = res_mall_actual[res_mall_actual['SEMANA_ISO'] == sem].copy()
            titulo = f"Gantt Semanal Estatico ({regla_actual}) - Semana {sem}"
        except:
            print("Semana invalida.")
            return

    if df_f.empty and df_m.empty:
        print("No hay remisiones en este periodo.")
        return

    df_f['Maquina'] = 'FIGURADO'
    df_m['Maquina'] = 'MALLAS'
    df_gantt = pd.concat([df_f, df_m])

    fig = px.timeline(
        df_gantt, x_start="INICIO_REAL", x_end="FIN_REAL",
        y="Maquina", color="Nº REMISION", title=titulo,
        hover_data=["Nº REMISION", "FECHA_PROMESA"],
        template="plotly_white"
    )
    fig.update_yaxes(autorange="reversed")
    fig.update_layout(showlegend=False, height=450, xaxis_title="Cronograma")
    fig.show()

def menu():
    global res_fig_actual, res_mall_actual, regla_actual
    res_fig_actual, res_mall_actual = evaluar_regla_semanal(regla_actual)

    while True:
        print(f"\n{'='*75}\n TALLER 1 - SOLUCION PUNTO D (ESTATICO)\n{'='*75}")
        print(f"Regla Activa en Memoria: {regla_actual}")
        print("1. Rastrear estado de una Remision (Regla Activa)")
        print("2. Generar Diagrama de Gantt Interactivo (Regla Activa)")
        print("3. Comparar 8 reglas CONSOLIDADO TOTAL")
        print("4. Comparar 8 reglas SEMANAL (Detalle por Semana)")
        print("5. Comparar 8 reglas DIARIA  (Detalle por Dia)")
        print("6. Cambiar Regla Activa")
        print("7. Salir")

        op = input("\nSeleccione una opcion: ")

        if op == "1":
            n = input("Ingrese el Nº de Remision: ").strip()
            f = res_fig_actual[res_fig_actual['Nº REMISION'] == n]
            m = res_mall_actual[res_mall_actual['Nº REMISION'] == n]
            if f.empty and m.empty:
                print(f"Remision {n} no encontrada.")
            else:
                f_fin = f['FIN_REAL'].max() if not f.empty else pd.Timestamp.min
                m_fin = m['FIN_REAL'].max() if not m.empty else pd.Timestamp.min
                final = max(f_fin, m_fin)
                promesa = (f.iloc[0] if not f.empty else m.iloc[0])['FECHA_PROMESA']
                print(f"\n--- REPORTE REMISION {n} ---")
                print(f"Entrega Prometida: {promesa.strftime('%Y-%m-%d %H:%M')}")
                print(f"Terminacion Real:  {final.strftime('%Y-%m-%d %H:%M')}")
                print(f"Estado: {'A TIEMPO' if final <= promesa else 'RETRASADO'}")

        elif op == "2":
            sub = input("\nDesea ver Gantt 1. Diario o 2. Semanal?: ")
            graficar_gantt_interactivo(sub)

        elif op == "3":
            reglas = ['FCFS', 'SPT', 'WSPT', 'LPT', 'EDD', 'MST', 'CR', 'WLPT']
            resultados = []
            for r in reglas:
                df_f, df_m = evaluar_regla_semanal(r)
                df_total = pd.concat([df_f, df_m])
                wC, wT, U = calcular_objetivos(df_total)
                resultados.append({'Regla': r, 'Suma_Wj_Cj': wC, 'Suma_Wj_Tj': wT, 'Total_Uj': U})
            print("\n--- COMPARATIVA CONSOLIDADA TOTAL ---")
            print(pd.DataFrame(resultados).to_string(index=False, float_format="%.2f"))

        elif op == "4":
            reglas = ['FCFS', 'SPT', 'WSPT', 'LPT', 'EDD', 'MST', 'CR', 'WLPT']
            resultados = []
            for r in reglas:
                df_f, df_m = evaluar_regla_semanal(r)
                df_total = pd.concat([df_f, df_m])
                for sem in sorted(df_total['SEMANA_ISO'].unique()):
                    df_sem = df_total[df_total['SEMANA_ISO'] == sem].copy()
                    wC, wT, U = calcular_objetivos(df_sem)
                    resultados.append({'Regla': r, 'Periodo': f"Semana {sem}", 'Wj_Cj': wC, 'Wj_Tj': wT, 'Uj': U})
                wC_t, wT_t, U_t = calcular_objetivos(df_total)
                resultados.append({'Regla': f"[{r}]", 'Periodo': 'TOTAL', 'Wj_Cj': wC_t, 'Wj_Tj': wT_t, 'Uj': U_t})
            print("\n--- COMPARATIVA SEMANAL ---")
            print(pd.DataFrame(resultados).to_string(index=False, float_format="%.2f"))

        elif op == "5":
            reglas = ['FCFS', 'SPT', 'WSPT', 'LPT', 'EDD', 'MST', 'CR', 'WLPT']
            resultados = []
            for r in reglas:
                df_f, df_m = evaluar_regla_diaria(r)
                df_total = pd.concat([df_f, df_m])
                for dia in sorted(df_total['FECHA'].dt.date.unique()):
                    df_dia = df_total[df_total['FECHA'].dt.date == dia].copy()
                    wC, wT, U = calcular_objetivos(df_dia)
                    resultados.append({'Regla': r, 'Periodo': str(dia), 'Wj_Cj': wC, 'Wj_Tj': wT, 'Uj': U})
                wC_t, wT_t, U_t = calcular_objetivos(df_total)
                resultados.append({'Regla': f"[{r}]", 'Periodo': 'TOTAL', 'Wj_Cj': wC_t, 'Wj_Tj': wT_t, 'Uj': U_t})
            print("\n--- COMPARATIVA DIARIA ---")
            with pd.option_context('display.max_rows', None):
                print(pd.DataFrame(resultados).to_string(index=False, float_format="%.2f"))

        elif op == "6":
            print("\n1:FCFS | 2:SPT | 3:WSPT | 4:LPT | 5:EDD | 6:MST | 7:CR | 8:WLPT")
            sel = input("Seleccione regla (1-8): ").strip()
            mapa = {'1': 'FCFS', '2': 'SPT', '3': 'WSPT', '4': 'LPT', '5': 'EDD', '6': 'MST', '7': 'CR', '8': 'WLPT'}
            if sel in mapa:
                regla_actual = mapa[sel]
                res_fig_actual, res_mall_actual = evaluar_regla_semanal(regla_actual)
                print(f"Regla cambiada a {regla_actual}.")
            else:
                print("Opcion no valida.")

        elif op == "7":
            break

if __name__ == "__main__":
    menu()

#////////////////////////////////////////////
#
#  Punto E
#////////////////////////////////////////////


import pandas as pd
import numpy as np
import plotly.express as px
from datetime import datetime
import io
import requests

# ==========================================
# 1. CARGA DE DATOS DESDE GITHUB
# ==========================================
url_github = "https://github.com/Fev23/Datos-entrada-Taller-Plan-Eduyn/raw/refs/heads/main/datos%20entrada%20A%20dias.xlsx"

try:
    print("Conectando con GitHub para extraer datos dinámicos...")
    response = requests.get(url_github)
    response.raise_for_status()
    df = pd.read_excel(io.BytesIO(response.content))
    print("Datos cargados exitosamente.\n")
except Exception as e:
    print(f"Error al conectar con GitHub: {e}")
    exit()

df.columns = [c.strip() for c in df.columns]
df['FECHA'] = pd.to_datetime(df['FECHA'])
df['Nº REMISION'] = df['Nº REMISION'].astype(str).str.strip()

# W_j: Importancia segun cantidad de tipos de producto
df['W_j'] = df['Cant tipos'].fillna(1).replace(0, 1)

# ==========================================
# 2. FECHAS DE ENTREGA d_j
# ==========================================
def calcular_promesa(rj):
    p = rj + pd.Timedelta(days=2)
    if p.weekday() == 6:
        p += pd.Timedelta(days=1)
    return p.replace(hour=15, minute=0, second=0)

df['FECHA_PROMESA'] = df['FECHA'].apply(calcular_promesa)
df['SEMANA_ISO'] = df['FECHA'].dt.isocalendar().week

# ==========================================
# 3. MOTOR DINÁMICO (Lote=5)
# ==========================================
def agregar_horas_habiles(fecha_inicio, horas):
    actual = fecha_inicio
    restante = horas
    while restante > 0:
        if actual.weekday() == 6:
            actual += pd.Timedelta(days=1)
            actual = actual.replace(hour=0, minute=0, second=0)
        dias_para_domingo = 6 - actual.weekday()
        proximo_domingo = (actual + pd.Timedelta(days=dias_para_domingo)).replace(hour=0, minute=0, second=0)
        horas_al_domingo = (proximo_domingo - actual).total_seconds() / 3600.0
        if restante <= horas_al_domingo:
            actual += pd.Timedelta(hours=restante)
            restante = 0
        else:
            actual = proximo_domingo + pd.Timedelta(days=1)
            restante -= horas_al_domingo
    return actual

def procesar_semana_dinamica(df_semana, col_pj, regla, batch_size=5):
    df_m = df_semana[df_semana[col_pj] > 0].copy()
    if df_m.empty: return []

    reloj = df_m['FECHA'].min() - pd.Timedelta(days=df_m['FECHA'].min().weekday())
    reloj = reloj.replace(hour=0, minute=0, second=0)

    finalizados = []
    unscheduled = df_m.copy()

    while not unscheduled.empty:
        if reloj.weekday() == 6:
            reloj += pd.Timedelta(days=1)
            reloj = reloj.replace(hour=0, minute=0, second=0)

        disp = unscheduled[unscheduled['FECHA'] <= reloj].copy()
        if disp.empty:
            reloj = unscheduled['FECHA'].min()
            continue

        dj_minus_t = (disp['FECHA_PROMESA'] - reloj).dt.total_seconds() / 3600.0
        pj = disp[col_pj]
        wj = disp['W_j']

        if regla == 'CR':
            disp['PRIORIDAD'] = dj_minus_t / pj
            asc = True
        elif regla == 'MST':
            disp['PRIORIDAD'] = dj_minus_t - pj
            asc = True
        elif regla == 'ATC':
            K, p_avg = 2.0, max(pj.mean(), 1e-5)
            slack = np.maximum(0, dj_minus_t - pj)
            disp['PRIORIDAD'] = (wj / pj) * np.exp(-slack / (K * p_avg))
            asc = False
        elif regla == 'COVERT':
            K, p_avg = 2.0, max(pj.mean(), 1e-5)
            slack = np.maximum(0, dj_minus_t - pj)
            cov_factor = np.maximum(0, 1 - (slack / (K * p_avg)))
            disp['PRIORIDAD'] = (wj / pj) * cov_factor
            asc = False
        elif regla == 'RSI':
            slack = dj_minus_t - pj
            time_to_due = np.maximum(1e-5, dj_minus_t)
            disp['PRIORIDAD'] = slack / time_to_due
            asc = True

        disp = disp.sort_values(by=['PRIORIDAD', 'W_j'], ascending=[asc, False], kind='stable')
        batch = disp.head(batch_size)

        for idx, row in batch.iterrows():
            if reloj.weekday() == 6:
                reloj += pd.Timedelta(days=1)
                reloj = reloj.replace(hour=0, minute=0, second=0)
            inicio_tarea = reloj
            reloj = agregar_horas_habiles(reloj, row[col_pj])
            row_copy = row.copy()
            row_copy['INICIO_REAL'] = inicio_tarea
            row_copy['FIN_REAL'] = reloj
            row_copy['C_j_horas'] = (reloj - row_copy['FECHA']).total_seconds() / 3600.0
            finalizados.append(row_copy)
            unscheduled = unscheduled.drop(idx)
    return finalizados

# ==========================================
# 4. EVALUACIÓN Y MENÚ (SE MANTIENEN IGUAL)
# ==========================================
def calcular_objetivos_punto_e(df_resultados):
    if df_resultados.empty: return 0, 0, 0
    df_resultados['T_j'] = np.maximum(0, (df_resultados['FIN_REAL'] - df_resultados['FECHA_PROMESA']).dt.total_seconds() / 3600.0)
    df_resultados['U_j'] = (df_resultados['T_j'] > 0).astype(int)
    sum_Wj_Cj = np.sum(df_resultados['W_j'] * df_resultados['C_j_horas'])
    sum_Wj_Tj = np.sum(df_resultados['W_j'] * df_resultados['T_j'])
    sum_Uj = np.sum(df_resultados['U_j'])
    return sum_Wj_Cj, sum_Wj_Tj, sum_Uj

def evaluar_regla_completa(regla):
    resultados_fig, resultados_mall = [], []
    for sem in df['SEMANA_ISO'].unique():
        df_sem = df[df['SEMANA_ISO'] == sem]
        resultados_fig.extend(procesar_semana_dinamica(df_sem, 'pj fig', regla))
        resultados_mall.extend(procesar_semana_dinamica(df_sem, 'pj mall', regla))
    return pd.DataFrame(resultados_fig), pd.DataFrame(resultados_mall)

res_fig_actual, res_mall_actual = pd.DataFrame(), pd.DataFrame()
regla_actual = "CR"

def graficar_gantt_interactivo(modo):
    if res_fig_actual.empty and res_mall_actual.empty:
        print("Debe ejecutar una regla primero.")
        return
    if modo == "1":
        fecha = input("Ingrese fecha (AAAA-MM-DD): ").strip()
        df_f = res_fig_actual[res_fig_actual['INICIO_REAL'].dt.strftime('%Y-%m-%d') == fecha].copy()
        df_m = res_mall_actual[res_mall_actual['INICIO_REAL'].dt.strftime('%Y-%m-%d') == fecha].copy()
    else:
        try:
            sem = int(input("Ingrese semana: "))
            df_f = res_fig_actual[res_fig_actual['SEMANA_ISO'] == sem].copy()
            df_m = res_mall_actual[res_mall_actual['SEMANA_ISO'] == sem].copy()
        except: return
    if df_f.empty and df_m.empty: return
    df_f['Maquina'], df_m['Maquina'] = 'FIGURADO', 'MALLAS'
    fig = px.timeline(pd.concat([df_f, df_m]), x_start="INICIO_REAL", x_end="FIN_REAL", y="Maquina", color="Nº REMISION", template="plotly_white")
    fig.show()

def menu():
    global res_fig_actual, res_mall_actual, regla_actual
    res_fig_actual, res_mall_actual = evaluar_regla_completa(regla_actual)
    while True:
        print(f"\n{'='*70}\n TALLER 1 - PUNTO E (DINÁMICO GITHUB)\n{'='*70}")
        print("1. Rastrear Remision | 2. Gantt | 3. Consolidado | 4. Semanal | 5. Cambiar Regla | 6. Salir")
        op = input("\nSeleccione: ")
        if op == "1":
            n = input("Nº Remisión: ").strip()
            f, m = res_fig_actual[res_fig_actual['Nº REMISION'] == n], res_mall_actual[res_mall_actual['Nº REMISION'] == n]
            if not f.empty or not m.empty:
                f_fin = f['FIN_REAL'].max() if not f.empty else pd.Timestamp.min
                m_fin = m['FIN_REAL'].max() if not m.empty else pd.Timestamp.min
                final = max(f_fin, m_fin)
                print(f"Terminación: {final}")
        elif op == "2": graficar_gantt_interactivo(input("1. Diario 2. Semanal: "))
        elif op == "3":
            for r in ['CR', 'MST', 'ATC', 'COVERT', 'RSI']:
                df_f, df_m = evaluar_regla_completa(r)
                wC, wT, U = calcular_objetivos_punto_e(pd.concat([df_f, df_m]))
                print(f"{r}: WjCj={wC:.0f}, WjTj={wT:.0f}, Uj={U}")
        elif op == "5":
            sel = input("1.CR 2.MST 3.ATC 4.COVERT 5.RSI: ")
            regla_actual = {'1':'CR','2':'MST','3':'ATC','4':'COVERT','5':'RSI'}.get(sel, 'CR')
            res_fig_actual, res_mall_actual = evaluar_regla_completa(regla_actual)
        elif op == "6": break

if __name__ == "__main__":
    menu()

#///////////////////////////////////////////////
#
#    Punto F con posible comparativa para mejorar los costos
#
#//////////////////////////////////////////////
import pandas as pd
import numpy as np
import io
import requests
import plotly.express as px
from datetime import datetime, timedelta

# 1. CARGA Y PREPARACIÓN DE DATOS (GitHub)
url = "https://github.com/Fev23/Datos-entrada-Taller-Plan-Eduyn/raw/refs/heads/main/Apartado%202.xlsx"
try:
    response = requests.get(url)
    df = pd.read_excel(io.BytesIO(response.content))
except:
    print("Error al cargar datos. Verifique la conexión.")
    exit()

df.columns = [c.strip() for c in df.columns]

# Parámetros del modelo
V1, V2 = 1.0, 1.5
ALPHA, H, W = 40000, 130000, 200000

df['FECHA_DT'] = pd.to_datetime(df['FECHA'])
T_INICIO = df['FECHA_DT'].min().replace(hour=0, minute=0)

def calcular_promesa(f):
    p = f + pd.Timedelta(days=2)
    if p.weekday() == 6: p += pd.Timedelta(days=1)
    return p.replace(hour=15, minute=0, second=0)

df['PROMESA_H'] = (df['FECHA_DT'].apply(calcular_promesa) - T_INICIO).dt.total_seconds() / 3600
df = df.sort_values(by=['Cant tipos', 'p_j'], ascending=[False, True]).reset_index(drop=True)

# 2. MOTOR DE SIMULACIÓN
def simular(factor_v):
    reloj, c_ent, c_ant, c_tar = 0, 0, 0, 0
    batch, data_rastreo = [], []
    contador = 1

    for idx, row in df.iterrows():
        pj_real = row['p_j'] / factor_v
        inicio_job = reloj
        reloj += pj_real
        batch.append({
            'id': str(row['Nº REMISION']),
            'inicio': inicio_job,
            'fin': reloj,
            'due': row['PROMESA_H']
        })

        # Lógica de grupos: cada 6 horas o al final
        if reloj % 6.0 < pj_real or idx == len(df) - 1:
            d_k = reloj
            for job in batch:
                tardanza = max(0, d_k - job['due'])
                c_ent += (d_k * ALPHA) / len(batch)
                c_ant += (d_k - job['fin']) * H
                c_tar += tardanza * W

                # Cálculo de tiempos reales para el Gantt (basado en T_INICIO)
                t_real_inicio = T_INICIO + timedelta(hours=job['inicio'])
                t_real_fin = T_INICIO + timedelta(hours=job['fin'])
                t_real_despacho = T_INICIO + timedelta(hours=d_k)

                data_rastreo.append({
                    'Secuencia': contador,
                    'Remision': job['id'],
                    'Inicio_DT': t_real_inicio,
                    'Fin_DT': t_real_fin,
                    'Despacho_DT': t_real_despacho,
                    'Fin_Prod': round(job['fin'], 2),
                    'Salida_Batch': round(d_k, 2),
                    'Retraso_H': round(tardanza, 2),
                    'Costo_T': round(tardanza * W, 0)
                })
                contador += 1
            batch = []
    return [c_ent, c_ant, c_tar], pd.DataFrame(data_rastreo)

# Ejecución de escenarios
costos_v1, rastreo_v1 = simular(V1)
costos_v2, rastreo_v2 = simular(V2)

# 3. FUNCIONES DE VISUALIZACIÓN
def mostrar_reporte():
    print("\n" + "="*65)
    print(f"{'REPORTE DE COSTOS COMPUESTOS (Chand & Chhajed)':^65}")
    print("="*65)
    print(f"{'Componente':<20} | {'Velocidad x'+str(V1):>18} | {'Velocidad x'+str(V2):>18}")
    print("-" * 65)
    nombres = ["Fecha Entrega (α)", "Anticipación (h)", "Tardanza (w)"]
    for i in range(3):
        print(f"{nombres[i]:<20} | ${costos_v1[i]:>17,.0f} | ${costos_v2[i]:>17,.0f}")
    print("-" * 65)
    print(f"{'TOTAL COMPUESTO':<20} | ${sum(costos_v1):>17,.0f} | ${sum(costos_v2):>17,.0f}")
    print("="*65)

def graficar_gantt_diario():
    print("\nFechas disponibles en el sistema:")
    fechas_disp = rastreo_v1['Inicio_DT'].dt.date.unique()
    for i, f in enumerate(fechas_disp): print(f"[{i}] {f}")

    try:
        idx = int(input("\nSeleccione el índice del día a graficar: "))
        fecha_sel = fechas_disp[idx]

        # Filtramos datos de la Velocidad Normal para ese día
        df_gantt = rastreo_v1[rastreo_v1['Inicio_DT'].dt.date == fecha_sel].copy()

        if df_gantt.empty:
            print("No hay datos para esa fecha.")
            return

        # Creamos el Gantt
        fig = px.timeline(
            df_gantt,
            x_start="Inicio_DT",
            x_end="Fin_DT",
            y="Remision",
            color="Salida_Batch",
            title=f"Programación Diaria (Velocidad Normal) - {fecha_sel}",
            labels={'Salida_Batch': 'Hora de Despacho (Acum)'},
            template="plotly_white"
        )
        fig.update_yaxes(autorange="reversed")
        fig.show()
    except:
        print("[!] Entrada no válida.")

# 4. MENÚ PRINCIPAL
def menu_principal():
    mostrar_reporte()
    while True:
        print("\n" + "-"*30)
        print("SISTEMA DE GESTIÓN PUNTO F")
        print("-"*30)
        print("[1] Ver Reporte de Costos")
        print("[2] Rastrear Remisión")
        print("[3] Ver Gantt Diario (Velocidad Normal)")
        print("[4] Salir")
        opcion = input("\nSeleccione una opción: ")

        if opcion == '1':
            mostrar_reporte()
        elif opcion == '2':
            id_buscado = input("\nNº de Remisión: ").strip()
            res = rastreo_v2[rastreo_v2['Remision'] == id_buscado]
            if not res.empty:
                info = res.iloc[0]
                print(f"\nDETALLE (Velocidad x{V2}):")
                print(f"Secuencia: {info['Secuencia']} | Fin Prod: {info['Fin_Prod']}h | Despacho: {info['Salida_Batch']}h | Retraso: {info['Retraso_H']}h")
            else:
                print("[!] No encontrada.")
        elif opcion == '3':
            graficar_gantt_diario()
        elif opcion == '4':
            break

if __name__ == "__main__":
    menu_principal()